ManageIQ/manageiq-providers-openstack

Rakefile, lib/manageiq-providers-openstack.rb, spec/models/manageiq/providers/openstack/cloud_manager/metrics_capture_spec.rb, spec/models/manageiq/providers/openstack/cloud_manager/refresh_spec_common.rb, spec/models/manageiq/providers/openstack/infra_manager/metrics_capture_spec.rb, spec/spec_helper.rb
=> add manageiq-providers-openstack.rb

app/models/manageiq/providers/openstack/cloud_manager/refresh_parser.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1437624
=> Handle case where instance flavor is deleted

app/models/manageiq/providers/openstack/base_metrics_capture.rb
Network metrics are missing on the overcloud. This happened when
we switched from Ceilometer to Gnocchi.
Unlike Ceilometer, Gnocchi network metrics are associated with the
instance's network interface and not the instance. This patch adds
additional logic to query for the network interface's resource
meters if they are available.
Fixes BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1434681
=> Fix Gnocchi network metrics

spec/models/manageiq/providers/openstack/cloud_manager/cloud_volume_spec.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1441469
=> Update cloud volume test to accommodate core cloud volume model change

app/models/manageiq/providers/openstack/cloud_manager/provision/cloning.rb
Part of [Refactor MiqRequestTask::Dumping. #14547](https://github.com/ManageIQ/manageiq/pull/14547).
@miq-bot assign @gmcculloug 
@miq-bot add_label fine/yes, euwe/no
=> Rename dumpObj to dump_obj for MiqRequestTask.

app/models/manageiq/providers/openstack/network_manager/refresh_parser.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1449230
https://bugzilla.redhat.com/show_bug.cgi?id=1449725
https://bugzilla.redhat.com/show_bug.cgi?id=1449260
=> Allow HA envs to capture router/subnet relationship through port info

app/models/manageiq/providers/openstack/network_manager/security_group.rb
Raw commands and Tasks queues for create and delete
Adds rule parsing specific for Openstack network provider
=> Security Groups Rules: Create, delete tasks

app/models/manageiq/providers/openstack/network_manager/refresh_parser.rb
Populates source_security_group_id
https://github.com/ManageIQ/manageiq/issues/15030
=> Security Groups Inventory fix

app/models/manageiq/providers/openstack/network_manager/refresh_parser.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1454947
=> Add network:ha_router_replicated_interface when checking ports

app/models/manageiq/providers/openstack/infra_manager/orchestration_stack.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1447599
=> Fix checking of scaledown task state

config/settings.yml
Settings.yml file contains list of Openstack events. Moving from main repo to
Openstack provider repo.
Related to https://github.com/ManageIQ/manageiq-providers-openstack/issues/23
=> Import openstack events from main repo

app/models/manageiq/providers/openstack/network_manager/network_router.rb
Migrated from https://github.com/ManageIQ/manageiq/pull/13073
=> Network Router: More generic use of SupportsFeatureMixin

spec/models/manageiq/providers/openstack/cloud_manager/auth_key_pair_spec.rb
Fixes issue caused by changes in https://github.com/ManageIQ/manageiq/pull/15485
=> Update keypair spec test

.rspec, .rspec_ci, Rakefile, bin/setup, bin/update, config/settings.yml, lib/tasks_private/spec.rake, spec/spec_helper.rb
ran the generator again with
```bash
bundle exec rails g provider <name> --path ../
```
these are the changes.
=> run provider generator to sync changes from core

CHANGELOG.md
[skip ci]
@miq-bot add_label documentation
=> Updated for standardization of changlogs

app/models/manageiq/providers/openstack/cloud_manager/cloud_volume_backup.rb, spec/models/manageiq/providers/openstack/cloud_manager/cloud_volume_backup_spec.rb
Add cloud volume restore and delete raw actions.
https://github.com/ManageIQ/manageiq/pull/15891
=> Cloud volume backup

lib/manageiq/providers/openstack/legacy/openstack_handle/workflow_delegate.rb
Adding these methods provide a standard set of interfaces to
interact with the Workflow service. It will also allow us to remove
some duplicate code in Host.
=> Add execute_ and has_? workflow methods

app/models/manageiq/providers/openstack/cloud_manager/template.rb, spec/models/manageiq/providers/openstack/cloud_manager/template_spec.rb
Added `update` method for Image
=> Add update action for Image

app/models/manageiq/providers/openstack/cloud_manager/auth_key_pair.rb
Depends on https://github.com/ManageIQ/manageiq-providers-openstack/pull/110
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1466397
=> Trim key pair errors out of api responses

manageiq-providers-openstack.gemspec
For https://github.com/ManageIQ/manageiq/issues/15036
=> Allow Rails 5.1

app/models/manageiq/providers/openstack/infra_discovery.rb
Adds initial discovery for Openstack undercloud (ems infra) probing baremetal (Ironic) API 
https://bugzilla.redhat.com/show_bug.cgi?id=1212947
Depends upon https://github.com/ManageIQ/manageiq-network_discovery/pull/5
=> EMS infra: Openstack discover

app/models/manageiq/providers/openstack/manager_mixin.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1501329, which occurred because validation when creating a new provider is now done by calling `raw_connect` with the task queue, bypassing the exception translation that occurs with `verify_credentials` is called directly.
=> Translate exceptions from raw_connect

app/models/manageiq/providers/openstack/infra_manager/orchestration_stack.rb, spec/models/manageiq/providers/openstack/infra_manager/orchestration_stack_spec.rb
Moved logic into this repo for deciding whether to use Mistral
workflows if they are available or whether to use direct stack
update if the undercloud environment is OSP 9 or lower.
=> Move queuing logic for scaling from ui-classic

app/models/manageiq/providers/openstack/inventory/parser/cloud_manager.rb, app/models/manageiq/providers/openstack/refresh_parser_common/images.rb
Should fix https://bugzilla.redhat.com/show_bug.cgi?id=1510067
=> If an image name is "", use the image's id instead

CHANGELOG.md
=> [Changelog] Update master for Gaprindashvili Beta1 update

app/models/manageiq/providers/openstack/cloud_manager/refresh_worker.rb, app/models/manageiq/providers/openstack/cloud_manager/refresher.rb, spec/models/manageiq/providers/openstack/cloud_manager/refresh_worker_spec.rb
See https://github.com/ManageIQ/manageiq/pull/16465
=> Consolidate openstack refresh workers

app/models/manageiq/providers/openstack/cloud_manager/event_target_parser.rb, app/models/manageiq/providers/openstack/network_manager/event_target_parser.rb, spec/models/manageiq/providers/openstack/cloud_manager/event_target_parser_spec.rb, spec/models/manageiq/providers/openstack/network_manager/event_target_parser_spec.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1531547
=> Correct the paths that event target IDs are parsed from

app/models/manageiq/providers/openstack/infra_manager/host.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1504131
Archived nodes have no ems, so don't try to contact the (nonexistent) provider.
Just delete the AR object.
=> bz 1504131: For archived nodes, just delete AR object on remove

locale/es/ManageIQ_Providers_Openstack.po, locale/fr/ManageIQ_Providers_Openstack.po
This PR contains final translation fixes / polishing for Gaprindashvili GA
=> [GAPRINDASHVILI] Final translations for gaprindashvili

app/models/manageiq/providers/openstack/infra_discovery.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1212947
=> Infra discovery: Port scan needs trailing FF/LN

app/models/manageiq/providers/openstack/discovery.rb, lib/manageiq-providers-openstack.rb
-One discovery for entire provider
-Adjusted port scanner move/change
=> Discovery re-factor

locale/ManageIQ_Providers_Openstack.pot, locale/en/ManageIQ_Providers_Openstack.po, locale/es/ManageIQ_Providers_Openstack.po, locale/fr/ManageIQ_Providers_Openstack.po, locale/ja/ManageIQ_Providers_Openstack.po, locale/pt_BR/ManageIQ_Providers_Openstack.po, locale/zh_CN/ManageIQ_Providers_Openstack.po
Updated catalogs for next Gaprindashvili update release.
=> [GAPRINDASHVILI] Update gettext catalogs for Gaprindashvili update release

app/models/manageiq/providers/openstack/cloud_manager/template.rb
Reverts ManageIQ/manageiq-providers-openstack#236
=> Revert "Add delete_queue method for Template"

app/models/manageiq/providers/openstack/cloud_manager/cloud_volume/operations.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1530345
=> Parse volume attachment/detachment messages from fog responses

lib/manageiq/providers/openstack/legacy/openstack_handle/handle.rb, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_legacy_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_legacy_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_network_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_stack_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_tenant_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_vm_targeted_refresh.yml
https://bugzilla.redhat.com/show_bug.cgi?id=1561637
=> Avoid tenant discovery recursion

locale/es/ManageIQ_Providers_Openstack.po, locale/fr/ManageIQ_Providers_Openstack.po, locale/ja/ManageIQ_Providers_Openstack.po, locale/pt_BR/ManageIQ_Providers_Openstack.po, locale/zh_CN/ManageIQ_Providers_Openstack.po
Up-to-date translations for next Gaprindashvili update release.
=> [GAPRINDASHVILI] Updated translations for gaprindashvili update

lib/manageiq/providers/openstack/legacy/openstack_handle/handled_list.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1571836
=> Catch Fog::Errors::NotFound in OpenstackHandle.handled_list

app/models/manageiq/providers/openstack/cloud_manager/flavor.rb
This is pluggable version of https://github.com/ManageIQ/manageiq/pull/16944
=> Add display name for flavor

spec/models/manageiq/providers/openstack/cloud_manager/refresher_rhos_havana_errors_spec.rb
Needed for https://github.com/ManageIQ/manageiq/pull/17472
=> Change expected partial refresh error expection

app/models/manageiq/providers/openstack/discovery.rb, spec/models/manageiq/providers/openstack/discovery_spec.rb
Adds discovery of ssl ports
Adds default ironic ssl port
https://bugzilla.redhat.com/show_bug.cgi?id=1212947
=> Infra Discovery: support for SSL

app/models/manageiq/providers/openstack/network_manager/cloud_network.rb, app/models/manageiq/providers/openstack/network_manager/cloud_subnet.rb
Added notifications for deleting Cloud Network and Cloud Subnet
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1470210
Depends on https://github.com/ManageIQ/manageiq/pull/17556
=> Add notifications for Subnets, Networks

app/models/manageiq/providers/openstack/cloud_manager.rb
Add sshkey support to OpenStack Cloud needed for v2v.
=> add sshkey support to OpenStack Cloud

app/models/manageiq/providers/openstack/cloud_manager/provision/cloning.rb, app/models/manageiq/providers/openstack/cloud_manager/provision/volume_attachment.rb, spec/models/manageiq/providers/openstack/cloud_manager/provision/volume_attachment_spec.rb
Fixes issues left over from https://github.com/ManageIQ/manageiq-providers-openstack/pull/223
Also fixes https://bugzilla.redhat.com/show_bug.cgi?id=1610736 in combination with https://github.com/ManageIQ/manageiq/pull/17822
=> Fix automatic cloud tenant placement

lib/manageiq/providers/openstack/engine.rb
See ManageIQ/manageiq-ui-classic#4496 for primary motivation.
=> Add plugin display name

app/models/manageiq/providers/openstack/inventory.rb, app/models/manageiq/providers/openstack/inventory/collector.rb, app/models/manageiq/providers/openstack/inventory/parser.rb, app/models/manageiq/providers/openstack/inventory/persister.rb
Move ManagerRefresh::Inventory to ManageIQ::Providers::Inventory
=> Move Inventory to ManageIQ::Providers

app/models/manageiq/providers/openstack/network_manager/cloud_network.rb
Format error when physical network unknown for flat.
https://bugzilla.redhat.com/show_bug.cgi?id=1540692
=> Format error when physical network unknown for flat

app/models/manageiq/providers/openstack/cloud_manager/event_target_parser.rb, app/models/manageiq/providers/openstack/inventory.rb, app/models/manageiq/providers/openstack/inventory/collector/target_collection.rb, app/models/manageiq/providers/openstack/network_manager/event_target_parser.rb, app/models/manageiq/providers/openstack/storage_manager/cinder_manager/event_target_parser.rb, spec/models/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_spec.rb, spec/models/manageiq/providers/openstack/cloud_manager/stubbed_refresher_spec.rb, spec/models/manageiq/providers/openstack/network_manager/cloud_subnet_refresh_spec.rb
Move ManagerRefresh to InventoryRefresh
Depends on:
=> Move ManagerRefresh to InventoryRefresh

lib/manageiq/providers/openstack/legacy/events/openstack_rabbit_event_monitor.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1538058
If rabbitmq is using durable queue/exchanges, they must be opened
on the ManageIQ end with durable => true. If exchange creation
fails with Bunny::PreconditionFailed, retry with durable=>true.
=> bug 1538058: Retry bunny queue initialization for durable queues

app/models/manageiq/providers/openstack/cloud_manager/cloud_tenant.rb
@kbrock @Ladas Please sanity check this, I don't write many queries these days.
=> Replace inefficient default_security_group sort with join

app/models/manageiq/providers/openstack/storage_manager/cinder_manager.rb
See https://github.com/ManageIQ/manageiq-ui-classic/pull/4536 and https://github.com/ManageIQ/manageiq/pull/18000
=> Support the :cinder_volume_types feature in the CinderManager

app/models/manageiq/providers/openstack/inventory/collector/cloud_manager.rb, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_legacy_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_legacy_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_network_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_port_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_router_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_stack_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_tenant_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_vm_targeted_refresh.yml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1632849
=> Get images with pagination loop

app/models/manageiq/providers/openstack/cloud_manager/provision_workflow.rb, spec/models/manageiq/providers/openstack/cloud_manager/provision_workflow_spec.rb
This is a separate PR for Gaprindashvili branch.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1629124
master PR: https://github.com/ManageIQ/manageiq-providers-openstack/pull/344
@aufi
=> [Gaprindashvili]Use empty name if only size provided

app/models/manageiq/providers/openstack/cloud_manager/flavor.rb
@miq_bot add_label internationalization, hammer/yes
=> Don't use string interpolations inside gettext strings

app/models/manageiq/providers/openstack/identity_sync_mixin.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1635635
Manual changes after prior sync could result in the auto-generated
MiqGroup name/description duplicating existing values. If the auto-
generated name results in a uniqueness constraint violation, use
a timestamped name instead.
=> BZ 1635635 Avoid uniqueness constraint violations in sync_users

app/models/manageiq/providers/openstack/infra_manager/host.rb, spec/models/manageiq/providers/openstack/infra_manager/host_spec.rb
Container statuses should also be parsed during SSA, condition on line 145 should also handle cases with hybrid deployment.
https://bugzilla.redhat.com/show_bug.cgi?id=1573507
=> Parse containerized openstack services

CHANGELOG.md
=> [Changelog] Update for Sprint 98, H-B2, and G6

lib/manageiq/providers/openstack/legacy/openstack_handle.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1652574
=> Require 'parallel' in the OpenstackHandle

app/models/manageiq/providers/openstack/inventory/collector/target_collection.rb
Already incorporated into https://github.com/ManageIQ/manageiq-providers-openstack/pull/395
=> Fix autocomplete error in targeted Cloud Volume collection

app/models/manageiq/providers/openstack/inventory/collector/target_collection.rb, lib/vcr_recorder.rb, spec/models/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_spec.rb, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_legacy_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_legacy_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_network_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_port_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_router_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_tenant_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_vm_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_volume_targeted_refresh.yml
Backport PR for https://github.com/ManageIQ/manageiq-providers-openstack/pull/386
@simaishi
=> [HAMMER] When doing targeted refresh of a volume, refresh any attached VMs

app/models/manageiq/providers/openstack/inventory/collector/target_collection.rb, spec/models/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_spec.rb, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_legacy_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_legacy_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_network_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_port_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_router_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_stack_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_tenant_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_vm_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_volume_targeted_refresh.yml
Backport of https://github.com/ManageIQ/manageiq-providers-openstack/pull/422
https://bugzilla.redhat.com/show_bug.cgi?id=1662126
=> [HAMMER] Targeted refresh: Collect tenant ems references last

CHANGELOG.md
=> [Changelog] Update for Sprit 102

app/models/manageiq/providers/openstack/inventory/collector.rb, app/models/manageiq/providers/openstack/inventory/collector/cloud_manager.rb, app/models/manageiq/providers/openstack/inventory/collector/storage_manager/cinder_manager.rb, app/models/manageiq/providers/openstack/inventory/collector/target_collection.rb, lib/manageiq/providers/openstack/legacy/openstack_handle/handle.rb, spec/models/manageiq/providers/openstack/cloud_manager/stubbed_refresher_spec.rb, spec/models/manageiq/providers/openstack/network_manager/cloud_subnet_refresh_spec.rb, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_legacy_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_legacy_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_network_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_port_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_router_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_stack_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_tenant_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_vm_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_volume_targeted_refresh.yml
The absence of volume, networking, or image services
from the service catalog should not cause refresh to
completely fail. This PR is intended to increase the
resiliency of the inventory collecting process when
optional services are missing.
=> Improve handling of missing services

manageiq-providers-openstack.gemspec
Bump fog openstack to 0.1.30
https://bugzilla.redhat.com/show_bug.cgi?id=1658480
=> [GAPRINDASHVILI] Bump fog openstack

manageiq-providers-openstack.gemspec
Bump fog openstack to 0.1.31
https://bugzilla.redhat.com/show_bug.cgi?id=1658480
=> [HAMMER] Bump fog openstack

spec/factories/orchestration_template.rb
FactoryBot 5.0 will remove static attributes, replacing with dynamic
=> Removal of static attributes in factories

app/models/manageiq/providers/openstack/inventory/parser/storage_manager/cinder_manager.rb, app/models/manageiq/providers/openstack/storage_manager/cinder_manager.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1660896
Depends on https://github.com/ManageIQ/manageiq/pull/18371 and https://github.com/ManageIQ/manageiq-schema/pull/324
=> Support volume multiattachment

app/models/manageiq/providers/openstack/manager_mixin.rb, spec/models/manageiq/providers/openstack/cloud_manager_spec.rb
@agrare @jrafanie Please review.
=> Remove references to MiqPassword

lib/manageiq/providers/openstack/legacy/events/openstack_ceilometer_event_monitor.rb
Timestamps returned in Events from Ceilometer/Panko service don't
contain Timezone information, but OpenStack expects it to use UTC [1].
It should be parsed as UTC to ensure it will not be considered as MIQ machine
local Timezone which could break time-based OpenStack Event queries.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1692892
[1] https://specs.openstack.org/openstack/api-wg/guidelines/time.html
=> Parse OpenStack Event Timestamps as UTC

lib/manageiq/providers/openstack/legacy/events/openstack_ceilometer_event_monitor.rb, spec/legacy/events/openstack_ceilometer_event_monitor_spec.rb
Ceilometer does not understand the 'all_tenants' query option,
which causes it to return no results when queried for events. This
commit causes that query option to only be used when talking to
Panko.
=> Exclude 'all_tenants' option when querying Ceilometer for events

lib/manageiq/providers/openstack/engine.rb
Change plugin common methods to class methods
=> Change plugin common methods to class methods

spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_legacy_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_legacy_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_network_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_port_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_router_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_stack_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_tenant_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_vm_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_volume_targeted_refresh.yml
Fresh VCRs for OpenStack Cloud were recorded.
Depends on https://github.com/ManageIQ/manageiq/pull/18934
=> Rerecord VCRs after factories change

app/models/manageiq/providers/openstack/infra_manager/host.rb
OSP15 replaced Docker with Podman. MIQ needs parse running containers on Nodes.
Commands were updated to use both Docker and Podman commands to get all running containers.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1720301
=> Fix OpenStack services list with Podman

app/models/manageiq/providers/openstack/cloud_manager/event_catcher.rb, app/models/manageiq/providers/openstack/cloud_manager/metrics_collector_worker.rb, app/models/manageiq/providers/openstack/cloud_manager/refresh_worker.rb, app/models/manageiq/providers/openstack/infra_manager/event_catcher.rb, app/models/manageiq/providers/openstack/infra_manager/metrics_collector_worker.rb, app/models/manageiq/providers/openstack/infra_manager/refresh_worker.rb, app/models/manageiq/providers/openstack/network_manager/event_catcher.rb, app/models/manageiq/providers/openstack/network_manager/metrics_collector_worker.rb, app/models/manageiq/providers/openstack/network_manager/refresh_worker.rb, app/models/manageiq/providers/openstack/storage_manager/cinder_manager/event_catcher.rb
Requires https://github.com/ManageIQ/manageiq/pull/19516
=> Rely on the default implementation of .ems_class

app/models/manageiq/providers/openstack/network_manager.rb
This was missed in d2579b762ca60a1bdf34c77f2a6283ceed539673
=> Remove the require_nested call for removed refresh worker

app/models/manageiq/providers/openstack/cloud_manager/scanning.rb, app/models/manageiq/providers/openstack/cloud_manager/scanning/job.rb, app/models/manageiq/providers/openstack/cloud_manager/vm_or_template_shared/scanning.rb, spec/models/manageiq/providers/openstack/cloud_manager/vm_scan_spec.rb
State Machine diagram for this subclass of VmScan.
=> Subclass VmScan job as ManageIQ::Providers::Openstack::CloudManager::Scanning::Job

app/models/manageiq/providers/openstack/cloud_manager/availability_zone.rb, spec/models/manageiq/providers/openstack/cloud_manager/availability_zone_spec.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1741237
=> Check for infra_ems before calculating block_storage_disk_capacity

app/models/manageiq/providers/openstack/cloud_manager.rb, app/models/manageiq/providers/openstack/infra_manager.rb, app/models/manageiq/providers/openstack/network_manager.rb, app/models/manageiq/providers/openstack/storage_manager/cinder_manager.rb
just what it says on the tin
@miq-bot add_label cleanup
=> remove rest of inventory object refresh

app/models/manageiq/providers/openstack/inventory/parser/cloud_manager.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1818004
=> Remove unused RefreshParserCommon::Images mixin

CHANGELOG.md
=> CHANGELOG for Sprint 133

app/models/manageiq/providers/openstack/cloud_manager.rb, app/models/manageiq/providers/openstack/infra_manager.rb, spec/models/manageiq/providers/openstack/cloud_manager_spec.rb, spec/models/manageiq/providers/openstack/infra_manager_spec.rb
Cross Repo Tests: https://github.com/ManageIQ/manageiq-cross_repo-tests/pull/106
Core PR: https://github.com/ManageIQ/manageiq/pull/20039
=> Make Provider Catalog Types Pluggable

app/models/manageiq/providers/openstack/manager_mixin.rb
This is the UI part of the STF event monitor, after https://github.com/ManageIQ/manageiq-ui-classic/pull/6698 gets merged, any form change can be addressed in the provider repo by editing the `params_for_create` method.
Unfortunately I have no access to a live STF provider and I had issues with the `qpid_proton` gem so I couldn't test this properly, @aufi can you please try this?
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/7000
@miq-bot assign @aufi
=> Update DDF form with the STF event monitor and adjust validation

lib/manageiq/providers/openstack/legacy/events/openstack_stf_event_monitor.rb
Fixes https://github.com/ManageIQ/manageiq-providers-openstack/issues/601
=> Delay load qpid_proton via extracted method

app/models/manageiq/providers/openstack/cloud_manager/refresh_worker.rb, app/models/manageiq/providers/openstack/infra_manager/refresh_worker.rb, spec/models/manageiq/providers/openstack/infra_manager/refresh_worker_spec.rb
Depends on: https://github.com/ManageIQ/manageiq/pull/20302
=> Move combined refresh workers to core

app/models/manageiq/providers/openstack/infra_manager/host.rb
Removing non actual code which was a fix for https://bugzilla.redhat.com/show_bug.cgi?id=1343553
=> Remove unneeded code

app/models/manageiq/providers/openstack/base_metrics_capture.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1840945
=> Cache metrics api call

app/models/manageiq/providers/openstack/inventory/parser/cloud_manager.rb, app/models/manageiq/providers/openstack/inventory/persister/definitions/cloud_collections.rb
Depends: https://github.com/ManageIQ/manageiq/pull/20396
=> Rename the key_pairs collection to auth_key_pairs

app/models/manageiq/providers/openstack/cloud_manager/base_template.rb, app/models/manageiq/providers/openstack/cloud_manager/template.rb
@agrare Please review.
Part of https://github.com/ManageIQ/manageiq/pull/20486
=> Move supports :provisioning to base class for other descendants

app/models/manageiq/providers/openstack/cloud_manager/provision_workflow.rb
Propably a UI change modified parameters passed to backend, updating
prepare provision parameters method to work with it.
=> Fix Volume auto deletion with VM

app/models/manageiq/providers/openstack/cloud_manager.rb, app/models/manageiq/providers/openstack/infra_manager.rb
https://github.com/ManageIQ/manageiq-ui-classic/issues/7277
=> Update DDF schema to version 2

app/models/manageiq/providers/openstack/base_metrics_capture.rb
Backport of https://github.com/ManageIQ/manageiq-providers-openstack/pull/600
=> [IVANCHUK] Cache metrics api call

.codeclimate.yml, .gitignore, .rubocop.yml, .rubocop_cc.yml, .travis.yml, README.md, Rakefile, bin/ci/after_script, lib/manageiq/providers/openstack/engine.rb, lib/tasks/README.md, lib/tasks_private/spec.rake, manageiq-providers-openstack.gemspec, spec/spec_helper.rb, spec/support/stub_amqp_helper.rb
=> Plugin Generator Updates

app/models/manageiq/providers/openstack/cloud_manager/template.rb, app/models/manageiq/providers/openstack/cloud_manager/volume_snapshot_template.rb, app/models/manageiq/providers/openstack/cloud_manager/volume_template.rb
This is pluggable version of https://github.com/ManageIQ/manageiq/pull/20475
=> Add missing model display names

.codeclimate.yml, .rubocop.yml, .rubocop_cc.yml, manageiq-providers-openstack.gemspec
Depends on: https://github.com/ManageIQ/miq_bot/pull/506
=> Switch to manageiq-style

app/models/manageiq/providers/openstack/cloud_manager.rb
Depends on: https://github.com/ManageIQ/manageiq/pull/20725
=> Mark the CloudManager with supports :cloud_tenants

spec/models/manageiq/providers/openstack/cloud_manager/provision/configuration_spec.rb
this is the last one of these references in this repo
=> rename remaining factorygirl to factorybot

app/models/manageiq/providers/openstack/cloud_manager.rb
Depends on https://github.com/ManageIQ/manageiq/pull/20747
=> Expose supports :create_flavor on the CloudManager

app/models/manageiq/providers/openstack/cloud_manager/vm.rb
Set the new supports pause feature added in https://github.com/ManageIQ/manageiq/pull/20754
=> Set supports pause feature

app/models/manageiq/providers/openstack/cloud_manager/vm.rb
As per https://github.com/ManageIQ/manageiq-providers-openstack/pull/651#pullrequestreview-553860671
fyi @himdel 
=> Make the snapshot description field required

spec/tools/environment_builders/openstack.rb, spec/tools/environment_builders/openstack/helper_methods.rb, spec/tools/environment_builders/openstack/interaction_methods.rb, spec/tools/environment_builders/openstack/services/base_data.rb, spec/tools/environment_builders/openstack/services/compute/builder.rb, spec/tools/environment_builders/openstack/services/compute/data.rb, spec/tools/environment_builders/openstack/services/identity/builder.rb, spec/tools/environment_builders/openstack/services/identity/builder/keystone_v2.rb, spec/tools/environment_builders/openstack/services/identity/builder/keystone_v3.rb, spec/tools/environment_builders/openstack/services/identity/data/keystone_v2.rb, spec/tools/environment_builders/openstack/services/identity/data/keystone_v3.rb, spec/tools/environment_builders/openstack/services/image/builder.rb, spec/tools/environment_builders/openstack/services/image/data.rb, spec/tools/environment_builders/openstack/services/network/builder.rb, spec/tools/environment_builders/openstack/services/network/builder/base.rb, spec/tools/environment_builders/openstack/services/network/builder/neutron.rb, spec/tools/environment_builders/openstack/services/network/builder/nova.rb, spec/tools/environment_builders/openstack/services/network/data/neutron.rb, spec/tools/environment_builders/openstack/services/network/data/nova.rb, spec/tools/environment_builders/openstack/services/orchestration/builder.rb, spec/tools/environment_builders/openstack/services/orchestration/data.rb, spec/tools/environment_builders/openstack/services/orchestration/test_template.yml, spec/tools/environment_builders/openstack/services/storage/builder.rb, spec/tools/environment_builders/openstack/services/storage/data.rb, spec/tools/environment_builders/openstack/services/volume/builder.rb, spec/tools/environment_builders/openstack/services/volume/data.rb, spec/tools/environment_builders/openstack/tests/interaction_methods_spec.rb, spec/tools/environment_builders/openstack_environments.rb, spec/tools/environment_builders/openstack_install_environments.rb, spec/tools/environment_builders/openstack_vcr.sh
Removed from core in ManageIQ/manageiq#20943
(from commit ManageIQ/manageiq@a26a849bdb17cc712f3f814aa0fd4d9f46c609a7)
@agrare Please review.
=> Move environment builder from core

config/settings.yml, lib/manageiq/providers/openstack/engine.rb
Move logger initialization and configuration into plugins
=> Move logger initialization and configuration into plugins

app/models/manageiq/providers/openstack/cinder_manager_mixin.rb, app/models/manageiq/providers/openstack/cloud_manager.rb, app/models/manageiq/providers/openstack/inventory/persister/definitions/storage_collections.rb, app/models/manageiq/providers/openstack/storage_manager/cinder_manager.rb, app/models/manageiq/providers/openstack/storage_manager/swift_manager.rb, app/models/manageiq/providers/openstack/swift_manager_mixin.rb
Merge together with: https://github.com/ManageIQ/manageiq/pull/20959
=> Don't subclass from core cinder/swift managers

lib/manageiq/providers/openstack/legacy/events/openstack_rabbit_event_monitor.rb
what the title says
@miq-bot add_label cleanup
=> remove extraneous require thread

app/models/manageiq/providers/openstack/network_manager.rb, app/models/manageiq/providers/openstack/network_manager/cloud_subnet.rb
Parent issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/6861
=> Implemented DDF for cloud subnets and added support mixin call

app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume.rb
https://github.com/ManageIQ/manageiq/pull/21181
=> Add CloudVolume supports update

app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume.rb
https://github.com/ManageIQ/manageiq-ui-classic/issues/7713
=> Add cloud volume create form size validation

.gitignore, config/secrets.defaults.yml, lib/manageiq/providers/openstack/engine.rb, spec/models/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_spec.rb, spec/models/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_spec.rb, spec/spec_helper.rb
https://github.com/ManageIQ/manageiq/issues/21157
=> Use pluggable provider secrets

app/models/manageiq/providers/openstack/cloud_manager.rb, app/models/manageiq/providers/openstack/infra_manager.rb
https://github.com/ManageIQ/manageiq/pull/21224
=> Add supports :metrics feature

app/models/manageiq/providers/openstack/cloud_manager/vm/operations/power.rb
Goes with https://github.com/ManageIQ/manageiq/pull/21260
=> Convert shelve operations to use SupportsFeatureMixin

systemd/manageiq-providers-openstack_cloud_manager_event_catcher@.service, systemd/manageiq-providers-openstack_cloud_manager_metrics_collector@.service, systemd/manageiq-providers-openstack_cloud_manager_refresh@.service, systemd/manageiq-providers-openstack_infra_manager_event_catcher@.service, systemd/manageiq-providers-openstack_infra_manager_metrics_collector@.service, systemd/manageiq-providers-openstack_infra_manager_refresh@.service, systemd/manageiq-providers-openstack_network_manager_event_catcher@.service, systemd/manageiq-providers-openstack_storage_manager_cinder_manager_event_catcher@.service
part of https://github.com/ManageIQ/manageiq-rpm_build/pull/157
using manageiq properties and still running as root (but very close to switching over to manageiq user)
=> add properties files to systemd

systemd/manageiq-providers-openstack_cloud_manager_event_catcher@.service, systemd/manageiq-providers-openstack_cloud_manager_metrics_collector@.service, systemd/manageiq-providers-openstack_cloud_manager_refresh@.service, systemd/manageiq-providers-openstack_infra_manager_event_catcher@.service, systemd/manageiq-providers-openstack_infra_manager_metrics_collector@.service, systemd/manageiq-providers-openstack_infra_manager_refresh@.service, systemd/manageiq-providers-openstack_network_manager_event_catcher@.service, systemd/manageiq-providers-openstack_storage_manager_cinder_manager_event_catcher@.service
=> run services as manageiq user

app/models/manageiq/providers/openstack/inventory/parser/cloud_manager.rb
=> Rename Flavor CPU attributes

app/models/manageiq/providers/openstack/network_manager/cloud_network.rb
Moved fields from react code to provider repo for add/edit cloud network form.
Before:
After:
@miq-bot add-label enhancement
=> Added fields for cloud network form

app/models/manageiq/providers/openstack/cloud_manager.rb
Add supports :storage_manager and function block_storage_manager for storage manager access on UI side: https://github.com/ManageIQ/manageiq-ui-classic/pull/7821/files
@miq-bot add-label enhancement
=> Add supports :storage_manager and block_storage_manager function to Openstack

app/models/manageiq/providers/openstack/inventory/parser/network_manager.rb
Fix for https://app.travis-ci.com/github/ManageIQ/manageiq-providers-openstack/jobs/533324862 after https://github.com/ManageIQ/manageiq-schema/pull/602
=> Make sure admin_state_up isn't `nil`

app/models/manageiq/providers/openstack/inventory/parser/cloud_manager.rb, app/models/manageiq/providers/openstack/inventory/persister/definitions/cloud_collections.rb
Required for backporting IBM PowerVC provider
=> Fix the template STI class for openstack subclasses

app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume.rb, app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume/operations.rb, spec/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume_spec.rb
Part of https://github.com/ManageIQ/manageiq/pull/21393
=> Convert cloud volume operations to SupportsFeatureMixin

app/models/manageiq/providers/openstack/cloud_manager/auth_key_pair.rb, spec/models/manageiq/providers/openstack/cloud_manager/auth_key_pair_spec.rb
Goes with https://github.com/ManageIQ/manageiq/pull/21457
=> Convert AuthKey operations to SupportsFeatureMixin

app/models/manageiq/providers/openstack/inventory/parser/cloud_manager.rb
=> refactoring code so the vm_details can be called from powervc subclass instance

app/models/manageiq/providers/openstack/inventory/collector/target_collection.rb
=> Move add_target and references to core collector

app/models/manageiq/providers/openstack/cloud_manager.rb, app/models/manageiq/providers/openstack/provider.rb
part of ManageIQ/manageiq#21573
=> converting supported_for_create to supports :create

app/models/manageiq/providers/openstack/network_manager/floating_ip.rb
add parameters for create and update to enable a data driven form for floating ips
currently create and update are working
=> Added Floating Ips Fields to Openstack Provider

app/models/manageiq/providers/openstack/network_manager/security_group.rb
Added fields for add and edit security groups form to provider repo.
=> Add fields for security groups form

app/models/manageiq/providers/openstack/inventory/persister/definitions/storage_collections.rb, app/models/manageiq/providers/openstack/inventory/persister/network_manager.rb
Required for: https://github.com/ManageIQ/manageiq/pull/21597
=> Fixes for auto-model-class

app/models/manageiq/providers/openstack/cloud_manager/host_aggregate.rb
=> Move HostAggregate.*_queue methods to core

app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume.rb
Morphy backport of https://github.com/ManageIQ/manageiq-providers-openstack/pull/772
=> [MORPHY]  Convert cloud volume operations to SupportsFeatureMixin

app/models/manageiq/providers/openstack/cloud_manager/auth_key_pair.rb
Merge together with: https://github.com/ManageIQ/manageiq/pull/21759
=> Refactor AuthKeyPair.raw_create_key_pair

app/models/manageiq/providers/openstack/storage_manager/swift_manager/cloud_object_store_container.rb
Fixes the missing notification type error when trying to create an openstack cloud object store container.
=> Fix notification error

app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume/operations.rb
part of https://github.com/ManageIQ/manageiq/pull/21841
=> rename CloudVolume#attach_volume to attach

app/models/manageiq/providers/openstack/infra_manager/host.rb
Required for:
* https://github.com/ManageIQ/manageiq/pull/21847
=> Convert host operations to supports

app/models/manageiq/providers/openstack/cloud_manager/template.rb, app/models/manageiq/providers/openstack/infra_manager.rb
part of https://github.com/ManageIQ/manageiq/issues/21179
converting AvaliableMixin to SupportsFeatureMixin
=> Convert validates to supports

app/models/manageiq/providers/openstack/infra_manager.rb
Continuing to remove uneeded memoization, with some additional translation fixes.
@miq-bot add-label najdorf/yes?
=> Removing Memoization

spec/models/manageiq/providers/openstack/cloud_manager/vm_spec.rb
part of https://github.com/ManageIQ/manageiq/issues/21179
=> rename Vm Operation context

lib/tasks_private/openstack.rake, spec/models/manageiq/providers/openstack/cloud_manager/refresher_spec.rb, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher/refresher_admin.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher/vm_target.yml
- fleshed out refresher spec to include more scenarios
- improve rake task by modularizing code and error handling
TODO:
@miq-bot add_labels enhancement, test
=> Refresher spec and rerecord task enhancements

app/models/manageiq/providers/openstack/cloud_manager.rb, app/models/manageiq/providers/openstack/cloud_manager/snapshot.rb
=> Subclass Snapshot under Openstack::CloudManager

app/models/manageiq/providers/openstack/cloud_manager/vm/resize.rb, spec/models/manageiq/providers/openstack/cloud_manager/vm_spec.rb
Part of https://github.com/ManageIQ/manageiq-ui-classic/issues/7603
Depends on:
https://github.com/ManageIQ/manageiq-ui-classic/pull/8452
Connected to:
https://github.com/ManageIQ/manageiq-api/pull/1181
https://github.com/ManageIQ/manageiq/pull/22122
=> vm resize feature refactored to work with ddf

app/models/manageiq/providers/openstack/infra_manager/host.rb
Introducing credential endpoints for host. Referencing [this](https://github.com/ManageIQ/manageiq-providers-openstack/blob/master/app/models/manageiq/providers/openstack/infra_manager/host.rb#L91-L93).
=> Introducing params_for_update schema fields for Hosts

app/models/manageiq/providers/openstack/infra_manager.rb
The UI is calling `verify_credentials_task` and not `validate_credentials_task`.
If we want this functionality, we need to move to `verify_credentials`
I have not tested this at all.
More of a conversation starter.
=> Drop validate_credentials_task

app/models/manageiq/providers/openstack/cloud_manager/orchestration_template.rb, app/models/manageiq/providers/openstack/helper_methods.rb, spec/models/manageiq/providers/openstack/cloud_manager/provision/volume_attachment_spec.rb
Part of https://github.com/ManageIQ/manageiq/issues/22696
=> Psych 4 support

manageiq-providers-openstack.gemspec
=> Allow rails 7 gems in gemspec

app/models/manageiq/providers/openstack/inventory/parser/cloud_manager.rb
When a VM is in `ERROR` state (and possibly other states) the vm.volume_attachments call may fail raising an
Fog::OpenStack::Compute::NotFound exception and causing the entire inventory refresh to fail. This rescue allows the inventory refresh to pass (and in the case of a VM in ERROR state, the VM will show up in ManageIQ inventory as 'non_operational').
=> Rescue VM volume attachments NotFound

manageiq-providers-openstack.gemspec
Pull in fix for invalid class `Util::RecursiveHotFileLoader` https://github.com/fog/fog-openstack/pull/541
Fixes https://github.com/ManageIQ/manageiq-providers-openstack/issues/904
=> Bump fog-openstack to v1.1.4

app/models/manageiq/providers/openstack/cloud_manager.rb, app/models/manageiq/providers/openstack/event_catcher_runner_mixin.rb, app/models/manageiq/providers/openstack/infra_manager.rb, app/models/manageiq/providers/openstack/network_manager.rb, app/models/manageiq/providers/openstack/storage_manager/cinder_manager.rb, config/settings.yml
https://github.com/ManageIQ/manageiq/pull/23320
=> Rename blacklisted event names

app/models/manageiq/providers/openstack/cloud_manager/cloud_tenant.rb, app/models/manageiq/providers/openstack/storage_manager/cinder_manager.rb
Part of:
- https://github.com/ManageIQ/manageiq/pull/23486
=> Use virtual_has_many instead of virtual_delegate for relations

app/models/manageiq/providers/openstack/storage_manager/cinder_manager.rb
Part of https://github.com/ManageIQ/manageiq/pull/23486
Fixes https://github.com/ManageIQ/manageiq-ui-classic/actions/runs/15789951644/job/44513894911#step:8:798
=> Through class name

.gitignore, config/secrets.defaults.yml, lib/manageiq/providers/openstack/engine.rb, spec/config/secrets.defaults.yml, spec/models/manageiq/providers/openstack/cloud_manager/refresher_spec.rb, spec/models/manageiq/providers/openstack/infra_manager/refresher_rhos_juno_spec.rb, spec/spec_helper.rb
=> Switch to use VcrSecrets helper from core

spec/config/secrets.defaults.yml, spec/models/manageiq/providers/openstack/infra_manager/refresher_rhos_juno_spec.rb
Follow-up to https://github.com/ManageIQ/manageiq-providers-openstack/pull/915/files#r2178492242
=> Port should be an int in vcr secrets

app/models/manageiq/providers/openstack/cloud_manager/cloud_tenant.rb
NOTE we used to do this in the form_params method:
https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/controllers/cloud_tenant_controller.rb#L122-L134
It doesn't appear we use this method anymore (@GilbertCherrie can this be deleted?)
Fixes https://github.com/ManageIQ/manageiq-providers-openstack/issues/913
=> Fix CloudTenant creation invalid parent_id

lib/manageiq/providers/openstack/engine.rb
Depends indirectly on: https://github.com/ManageIQ/manageiq/pull/23509
=> Drop to_s on engine paths

app/models/manageiq/providers/openstack/network_manager.rb
=> Move generic _queue methods into base NetworkManager
