ManageIQ/manageiq-providers-openstack

app/models/manageiq/providers/openstack/refresh_parser_common/images.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1438100
=> Set image name to id if name is nil in Glance

.rubocop_local.yml
Fixes:
```
$ rubocop -d app/models/manageiq/providers/openstack/inventory/collector/cloud_manager.rb 
For /home/bdunne/projects/redhat/manageiq-providers-openstack: configuration from /home/bdunne/projects/redhat/manageiq-providers-openstack/.rubocop.yml
configuration from /home/bdunne/projects/redhat/manageiq-providers-openstack/.rubocop-https---raw-githubusercontent-com-ManageIQ-guides-master--rubocop-base-yml
Default configuration from /home/bdunne/.gem/ruby/2.3.3/gems/rubocop-0.47.1/config/default.yml
Inheriting configuration from /home/bdunne/.gem/ruby/2.3.3/gems/rubocop-0.47.1/config/enabled.yml
Inheriting configuration from /home/bdunne/.gem/ruby/2.3.3/gems/rubocop-0.47.1/config/disabled.yml
Inheriting configuration from /home/bdunne/projects/redhat/manageiq-providers-openstack/.rub …
```
=> Add an exception for $fog_log

app/models/manageiq/providers/openstack/cloud_manager.rb, app/models/manageiq/providers/openstack/infra_manager.rb, spec/models/manageiq/providers/openstack/cloud_manager_spec.rb
Depends on:
Ensure managers change zone and provider region with cloud manager
The bug occurs when Cloud Manager is moved to a different zone. Then network and storage managers gets stuck and stop doing refresh.
Related to AWS BZ, same issue is for OpenStack:
https://bugzilla.redhat.com/show_bug.cgi?id=1439268
=> Ensure managers change zone and provider region with cloud manager

app/models/manageiq/providers/openstack/infra_manager/metrics_capture.rb, spec/models/manageiq/providers/openstack/infra_manager/metrics_capture_spec.rb, spec/tools/openstack_data/openstack_perf_data/irregular_interval.yml, spec/tools/openstack_data/openstack_perf_data/metadata_counters.yml, spec/tools/openstack_data/openstack_perf_data/multiple_collection_periods.yml, spec/tools/openstack_data/openstack_perf_data/standard.yml
Ceilometer's hardware.memory.used is calculated by subtracting free
memory from total memory.
See https://review.openstack.org/#/c/157257
Cached and buffer memory should be subtracted from
hardware.memory.used to get a more accurate representation of
memory that is utilized and can't be freed if there is memory
pressure.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1425951
=> Change memory utilization calculation for OpenStack infrastructure

config/settings.yml
Adding extracted settings.yml options related to Openstack
provider from original ManageIQ repo.
Resolves issue https://github.com/ManageIQ/manageiq-providers-openstack/issues/10
=> Move Openstack settings to own repo

app/models/manageiq/providers/openstack/cloud_manager/vm/operations.rb, app/models/manageiq/providers/openstack/cloud_manager/vm/operations/snapshot.rb, spec/models/manageiq/providers/openstack/cloud_manager/vm_spec.rb
The base snapshot code has checks that are inappropriate for OpenStack image snapshots.
https://bugzilla.redhat.com/show_bug.cgi?id=1443446
=> Override base snapshot concern

app/models/manageiq/providers/openstack/cloud_manager/vm/operations/snapshot.rb, spec/models/manageiq/providers/openstack/cloud_manager/vm_spec.rb
`supports_control?` catches a number of cases where we do not want to support snapshots:
https://github.com/ManageIQ/manageiq/blob/master/app/models/vm_or_template/operations.rb#L90-L104
This was causing travis failures on `ManageIQ/manageiq`: https://travis-ci.org/ManageIQ/manageiq/jobs/225161421#L639-L648
https://bugzilla.redhat.com/show_bug.cgi?id=1443446
=> Fix snapshot of VM without an EMS being supported

app/models/manageiq/providers/openstack/cloud_manager/cloud_tenant.rb, app/models/manageiq/providers/openstack/cloud_manager/provision_workflow.rb, app/models/manageiq/providers/openstack/network_manager.rb, app/models/manageiq/providers/openstack/network_manager/cloud_network/public.rb, spec/models/manageiq/providers/openstack/cloud_manager/provision_workflow_spec.rb, spec/models/manageiq/providers/openstack/cloud_manager/refresh_spec_common.rb
Allow all networks to be attached directly to a VM
Fixes BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1431370
=> Allow all networks to be attached directly to a VM

app/models/manageiq/providers/openstack/infra_manager/host.rb, spec/models/manageiq/providers/openstack/infra_manager/host_spec.rb
Openstack-status command which is used for getting Openstack
services status on the Host during SSA was removed.
PR https://github.com/ManageIQ/manageiq-gems-pending/pull/104
introduces another way for capuring services data. This commit
updates code to work with it.
https://bugzilla.redhat.com/show_bug.cgi?id=1434552
=> Fix Openstack Services on Host

app/models/manageiq/providers/openstack/infra_manager.rb
The Openstack::InfraManager model was using [alias EmsInfra](https://github.com/ManageIQ/manageiq/blob/master/app/models/aliases/ems_infra.rb) instead of the real subclass `ManageIQ::Providers::InfraManager`
Found while debugging issue https://github.com/ManageIQ/manageiq-automation_engine/issues/20 which is fixed by a similar change to the service model https://github.com/ManageIQ/manageiq-automation_engine/pull/22.
=> Change Openstack::InfraManager model to use real model for subclass

app/models/manageiq/providers/openstack/cloud_manager/provision/volume_attachment.rb
This change causes any volumes that are to be provisioned along with a VM to be provisioned in the same cloud tenant as that VM.
https://bugzilla.redhat.com/show_bug.cgi?id=1449915
@tzumainn
=> Provision VM-attached volumes in the same tenant as the VM

README.md, lib/tasks/openstack.rake, lib/vcr_recorder.rb
This allows developers to use one rake task `bundle exec rake app:manageiq:providers:openstack:vcr:rerecord` to re-record VCR cassettes.
=> Vcr recorder rake tasks

app/models/manageiq/providers/openstack/network_manager/security_group.rb, spec/models/manageiq/providers/openstack/network_manager/security_group_spec.rb
Adds `spec/models/manageiq/providers/openstack/network_manager/`
Adds security groups spec file with security group and firewall rules CRUD.
=> Adds security group tests

app/models/manageiq/providers/openstack/cloud_manager/event_catcher.rb, app/models/manageiq/providers/openstack/infra_manager/event_catcher.rb, app/models/manageiq/providers/openstack/manager_mixin.rb, app/models/manageiq/providers/openstack/network_manager/event_catcher.rb
MiqServer syncs processes each 15 seconds by default. This results into calling
available? method on event monitor. This was useful for AMQP subscriptions, but
it is not needed for Ceilometer and causes creating a lot of Keystone Auth tokens
on Openstack side.
This commit changes a method which is used for syncing event workers to verify
auth status on provider for Ceilometer and keeps original behavior for AMQP.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1451122
=> Fix Ceilometer Event Monitor sync calls

app/models/manageiq/providers/openstack/network_manager/security_group.rb
We can use source_security_group_id now that we have it in the inventory:
https://github.com/ManageIQ/manageiq-providers-openstack/pull/39
=> Add fw rule's remote group id for create/update

Gemfile, manageiq-providers-openstack.gemspec
Adding runtime dependencies forgotten in import code from manageiq-gems-pending repo.
Required to get https://github.com/ManageIQ/manageiq-gems-pending/pull/119 in.
=> Add missing deps from gems-pending repo

spec/spec_helper.rb
Spec helper from main repo contain code for AMQP stub, which is Openstack specific.
Moving to openstack provider repo and updating require path.
=> Fix spec helper AMQP stub method

config/settings.yml
This should fix the following errors on manageiq master:
```
1) EmsEvent.event_groups returns a list of groups
Failure/Error: expect(described_class.event_groups[:addition][:critical]).to include('CloneTaskEvent')
expected ["aggregate.addhost.end", "aggregate.create.end", "aggregate.removehost.end", "aggregate.updateprop.e..."AWS_EC2_Instance_DELETE", "TerminateInstances", "RunInstances", "virtualMachines_write_EndRequest"] to include "CloneTaskEvent"
2) EmsEvent.event_groups returns the provider event if configured
Failure/Error: expect(described_class.event_groups[:addition][:critical]).to include('CloneTaskEvent')
expected ["aggregate.addhost.end", "aggregate.create.end", "aggregate.removehost.end", "aggregate.updateprop.e...TerminateInstances", "RunInstances", …
```
=> fix indents so we don't overwrite the main settings.yml

Gemfile, app/models/manageiq/providers/openstack/manager_mixin.rb, spec/models/manageiq/providers/openstack/cloud_manager_spec.rb
Working on switching credential validation onto the queue using `raw_connect`. This will require passwords to be encrypted / decrypted.
See https://github.com/ManageIQ/manageiq-ui-classic/pull/1580 for related info / BZ
=> allow raw_connect to accept encrypted passwords

lib/manageiq/providers/openstack/legacy/openstack_handle/handle.rb, spec/legacy/openstack_handle/handle_spec.rb
Updates parameters used for auth process similar to OpenStack Client.
This change could fix issues with Auth against Domains with Keystone v3.
https://bugzilla.redhat.com/show_bug.cgi?id=1469860
=> [WIP] Update Keystone Domain related headers

app/models/manageiq/providers/openstack/network_manager.rb
Removes `create_network_router` which is redundant with `create`.
=> NetworkManager: SupportsFeatureMixin cleanup

spec/models/manageiq/providers/openstack/cloud_manager/stubbed_refresher_spec.rb, spec/models/manageiq/providers/openstack/openstack_stubs.rb
This is a set of tests for the inventory refresher with stubbed out calls that do not rely on the presence of a VCR. This is able to catch some stuff the current refreshers specs don't catch, like incorrectly setup relationships between different objects.
=> Add cloud refresher tests with stubbed out collector calls

app/models/manageiq/providers/openstack/inventory/collector/cloud_manager.rb, app/models/manageiq/providers/openstack/refresh_parser_common/flavors.rb
This PR prevents refresh from failing when a flavor's access list couldn't be retrieved due to a network issue or a nonexistent flavor. Fixes:
https://bugzilla.redhat.com/show_bug.cgi?id=1460683
=> Don't break refresh if a flavor couldn't be found

app/models/manageiq/providers/openstack/cloud_manager/flavor.rb, spec/models/manageiq/providers/openstack/cloud_manager/flavor_spec.rb
Adds specific methods for creating, deleting flavors.
=> creating, deleting flavors

app/models/manageiq/providers/openstack/inventory/parser/cloud_manager.rb
Assign only compact and unique list of hosts, to avoid rails
failures or duplication of the data.
Fixes:
https://github.com/ManageIQ/manageiq-providers-openstack/issues/70
=> Assign only compact and unique list of hosts

app/models/manageiq/providers/openstack/cloud_manager/provision/volume_attachment.rb, spec/models/manageiq/providers/openstack/cloud_manager/provision/volume_attachment_spec.rb
`do_volume_creation_check` assumes it will always get the requested volume object back from Fog, resulting in a thrown exception and an errored-out provisioning attempt if that assumption is violated due to the requested volume not being found. This fixes the assumption, allowing the provisioning workflow to continue and retry as normal.
This fixes the surface level issue in https://bugzilla.redhat.com/show_bug.cgi?id=1475260, though it doesn't explain why a 404 would be reported for an ID that came from Fog in the first place.
=> Handle case where do_volume_creation_check gets a nil from Fog

app/models/manageiq/providers/openstack/cloud_manager/provision_workflow.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1472420
=> Update provision requirements check to allow exact matches

Gemfile, lib/manageiq/providers/openstack/legacy/openstack_event_monitor.rb
Miq-module was moved from gems-pending repo to more_core_extensions
repo, updating require loading.
=> Update miq-module dependency to more_core_extensions

app/models/manageiq/providers/openstack/infra_manager/orchestration_stack.rb
These tasks execute Mistral workflows instead of invoking stack_update.
Depends on #54
=> Add scale_down and scale_up tasks to OrchestrationStack

app/models/manageiq/providers/openstack/network_manager/refresh_parser.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1488395
=> Old Refresh: Don't error out if a port refers to an unknown subnet.

app/models/manageiq/providers/openstack/cloud_manager.rb, app/models/manageiq/providers/openstack/cloud_manager/orchestration_template.rb, app/models/manageiq/providers/openstack/cloud_manager/vnfd_template.rb, spec/models/manageiq/providers/openstack/cloud_manager/orchestration_template_spec.rb, spec/models/manageiq/providers/openstack/cloud_manager/vnfd_template_spec.rb
Move the template classes to the corresponding provider repository.
This is a step before the migration.
https://bugzilla.redhat.com/show_bug.cgi?id=1417021
This is a refactor work but a step planned to fix above bugzilla issue.
=> Prepare to move OrchestrationTemplate to each provider

app/models/manageiq/providers/openstack/cloud_manager/flavor.rb, spec/models/manageiq/providers/openstack/cloud_manager/provision_workflow_spec.rb, spec/models/manageiq/providers/openstack/cloud_manager/refresh_spec_common.rb
Flavors info when selecting flavor in instance provisioning.
=> Add flavors info in instance provisioning

app/models/manageiq/providers/openstack/cloud_manager/event_target_parser.rb
This class parses refresh targets from EmsEvents. It's invoked from automate, see [here](https://github.com/ManageIQ/manageiq/blob/ef367b7e2e34750d3142494c42327c5c13da3dfb/app/models/ems_event/automate.rb#L5) and https://github.com/ManageIQ/manageiq-content/pull/159.
=> Add class for parsing refresh targets from EmsEvents

app/models/manageiq/providers/openstack/cloud_manager/provision/cloning.rb, app/models/manageiq/providers/openstack/cloud_manager/provision/volume_attachment.rb
If a volume or VM is provisioned in a tenant other than the default, then using `<collection>.get()` may fail to find them during the provisioning status check because the request is scoped to the wrong tenant. This PR scopes the request to use the tenant name from the provisioning request if it is a available.
This also fixes a performance problem with the cloning check, where in order to work around the scoping problem it was listing every server from every tenant. If the tenant name is available, then it will use `servers.get()` instead.
(Also some minor co-located lint fixes)
=> Check provisioning status with the correct tenant scoping

app/models/manageiq/providers/openstack/cloud_manager/vm.rb, spec/models/manageiq/providers/openstack/cloud_manager/vm_spec.rb
Use `terminated` as other providers, so that vm that is deleted won't continue to show on provider current active vms page, but in `archived` vms page
manageiq should be a tool of unification but not creating new divergences
Examples of `terminated` usage in other providers 
* https://github.com/ManageIQ/manageiq-providers-amazon/blob/7835e02d792216e7c380a49f7af609945c150618/app/models/manageiq/providers/amazon/cloud_manager/vm.rb#L12
* https://github.com/ManageIQ/manageiq-providers-vmware/blob/ba1583e269620784bdbe5e367e80fed61fc95f5d/app/models/manageiq/providers/vmware/cloud_manager/vm.rb#L13
Usage of `terminated`  in manageiq
* https://github.com/ManageIQ/manageiq/blob/c1549f0067bbdbcd6a3f9cfd89b8d0631744e57e/app/models/vm_or_template.rb#L309
=> Change vms state map deleted to 'terminated' instead of 'archived'

app/models/manageiq/providers/openstack/cloud_manager/template.rb, spec/models/manageiq/providers/openstack/cloud_manager/template_spec.rb
Added `create` method for Image
=> Add create action for Image

app/models/manageiq/providers/openstack/cloud_manager/template.rb, spec/models/manageiq/providers/openstack/cloud_manager/template_spec.rb
Fixed wrong service in [`delete`](https://github.com/ManageIQ/manageiq-providers-openstack/pull/88/files#diff-dc700e83d755312bb00d3e67ab440984R77) action for Image
=> Change Compute service to Image in delete action

app/models/manageiq/providers/openstack/cloud_manager/orchestration_stack.rb, app/models/manageiq/providers/openstack/cloud_manager/orchestration_template.rb, spec/fixtures/orchestration_templates/heat_parameters.json, spec/fixtures/orchestration_templates/heat_parameters.yml, spec/fixtures/orchestration_templates/vnfd_parameters.yml, spec/models/manageiq/providers/openstack/cloud_manager/orchestration_stack_spec.rb, spec/models/manageiq/providers/openstack/cloud_manager/orchestration_template_spec.rb, spec/models/manageiq/providers/openstack/cloud_manager/vnfd_template_spec.rb
Better support non-string parameter types including comma-delimited-list, number, boolean
https://bugzilla.redhat.com/show_bug.cgi?id=1489908
depends on ~~https://github.com/ManageIQ/manageiq/pull/16047~~
Update:
The work now also include better support Cloudformation template. So it is able to accept both HOT and Cloudformation templates in either JSON or YAML format.
The last commit fixed an error in spec test that references to a factory that has been removed from manageiq repo.
=> Enhance orchestration template parameter type support

app/models/manageiq/providers/openstack/infra_manager/event_parser.rb
Event parser now sets host_id attribute. It tries to find host by `ems_ref_obj` using `instance_id` attribute from event's payload.
[BZ link](https://bugzilla.redhat.com/show_bug.cgi?id=1377786)
=> Event parser sets host id

app/models/manageiq/providers/openstack/inventory/parser/cloud_manager.rb
Filter out resources with blank physical_resource_id.
Before we were ignoring those with:
https://github.com/Ladas/manageiq-providers-openstack/blob/d0799c4a5766650f2d3d149875c1b58f8a16040f/app/models/manageiq/providers/openstack/refresh_parser_common/orchestration_stacks.rb#L165
Without ignoring thise results in error :
[NoMethodError]: undefined method `ems_ref=' for nil:NilClass  Method:[block in method_missing]
=> Filter out resources with blank physical_resource_id

app/models/manageiq/providers/openstack/network_manager/floating_ip.rb
Needs to be merged along with https://github.com/ManageIQ/manageiq-ui-classic/pull/2312 to fix https://bugzilla.redhat.com/show_bug.cgi?id=1490918
=> Use floating_ip_address instead of name for creation messages

app/models/manageiq/providers/openstack/cloud_manager/cloud_tenant.rb
Makes the errors returned from the API when a cloud tenant action fails human readable. Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1476666, though problems of this category exist all over the place.
=> Trim error messages out of cloud tenant fog responses

app/models/manageiq/providers/openstack/cloud_manager.rb
Fix for bug 1494442 - symbol conversion error while detaching disks
from an openstack instance
https://bugzilla.redhat.com/show_bug.cgi?id=1494442
=> bug 1494442: fix attach/detach disks automate methods

app/models/manageiq/providers/openstack/manager_mixin.rb, spec/models/manageiq/providers/openstack/cloud_manager_spec.rb
The raw_connect method is used in provider validation; this change allows us to validate complex cases such as keystone v3 and ssl
Depends on https://github.com/ManageIQ/manageiq-ui-classic/pull/2394
https://bugzilla.redhat.com/show_bug.cgi?id=1500379
=> update raw connect method to accomodate OpenStack complexity

app/models/manageiq/providers/openstack/helper_methods.rb, app/models/manageiq/providers/openstack/network_manager/cloud_network.rb, app/models/manageiq/providers/openstack/network_manager/cloud_subnet.rb, app/models/manageiq/providers/openstack/network_manager/floating_ip.rb, app/models/manageiq/providers/openstack/network_manager/network_router.rb, app/models/manageiq/providers/openstack/network_manager/security_group.rb, spec/models/manageiq/providers/openstack/network_manager/cloud_network_spec.rb, spec/models/manageiq/providers/openstack/network_manager/cloud_subnet_spec.rb, spec/models/manageiq/providers/openstack/network_manager/floating_ip_spec.rb, spec/models/manageiq/providers/openstack/network_manager/network_router_spec.rb, spec/models/manageiq/providers/openstack/network_manager/security_group_spec.rb
This PR trims Neutron error messages out of fog responses, so that the UI can display readable messages instead of the mess of json and header info that currently appears. This is related to the problem described in https://bugzilla.redhat.com/show_bug.cgi?id=1476666, which will eventually be addressed as I go through the rest of the provider.
=> Trim neutron error messages out of fog responses

app/models/manageiq/providers/openstack/cloud_manager.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1471146 by checking for the presence of the network manager before attempting to modify it.
=> Only update tenant mapping for the network manager if it's present

app/models/manageiq/providers/openstack/cloud_manager/cloud_volume.rb, app/models/manageiq/providers/openstack/cloud_manager/cloud_volume/operations.rb, app/models/manageiq/providers/openstack/cloud_manager/cloud_volume_snapshot.rb, app/models/manageiq/providers/openstack/cloud_manager/vm.rb, app/models/manageiq/providers/openstack/cloud_manager/vm/operations.rb, app/models/manageiq/providers/openstack/cloud_manager/vm/operations/relocation.rb, app/models/manageiq/providers/openstack/helper_methods.rb, spec/models/manageiq/providers/openstack/cloud_manager/vm_spec.rb, spec/spec_helper.rb
This adds generic with_notification method to be used to wrap call for fog-openstack actions.
=> Add notifications for VM destroy, Cloud Volume and Cloud Volume Snapshot actions

app/models/manageiq/providers/openstack/cloud_manager/event_parser.rb, app/models/manageiq/providers/openstack/infra_manager/event_parser.rb, app/models/manageiq/providers/openstack/network_manager/event_parser.rb, spec/models/manageiq/providers/openstack/infra_manager/event_parser_spec.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1451437
=> update event parser code to deal with amqp messages

app/models/manageiq/providers/openstack/cloud_manager.rb
Creates notification with `vm_snapshot_success` type with Vm as `subject` for `create` and `remove` as `snapshot_op`.
Notification Type is defined in https://github.com/ManageIQ/manageiq/pull/16286 which is needed for this one.
Partially solves https://bugzilla.redhat.com/show_bug.cgi?id=1429313
=> Adds vm_snapshot_success Notification creation

app/models/manageiq/providers/openstack/cloud_manager/event_parser.rb, app/models/manageiq/providers/openstack/infra_manager/event_parser.rb, app/models/manageiq/providers/openstack/network_manager/event_parser.rb
Handles the case where the amqp message doesn't have the oslo.message key
https://bugzilla.redhat.com/show_bug.cgi?id=1451437
=> Fix for amqp events

app/models/manageiq/providers/openstack/cloud_manager/cloud_volume.rb, app/models/manageiq/providers/openstack/cloud_manager/cloud_volume_snapshot.rb, app/models/manageiq/providers/openstack/cloud_manager/flavor.rb, app/models/manageiq/providers/openstack/cloud_manager/host_aggregate.rb, app/models/manageiq/providers/openstack/cloud_manager/orchestration_stack.rb, app/models/manageiq/providers/openstack/cloud_manager/template.rb, app/models/manageiq/providers/openstack/cloud_manager/vm/associate_ip.rb, app/models/manageiq/providers/openstack/cloud_manager/vm/manage_security_groups.rb, app/models/manageiq/providers/openstack/cloud_manager/vm/resize.rb, app/models/manageiq/providers/openstack/cloud_manager/vnf.rb, app/models/manageiq/providers/openstack/infra_manager/host.rb, app/models/manageiq/providers/openstack/infra_manager/host/operations.rb, app/models/manageiq/providers/openstack/infra_manager/orchestration_stack.rb
Should make the UI prettier when things go wrong, instead of spraying poorly formatted JSON everywhere.
=> Trim error messages from fog responses for remaining models

Gemfile
While this doesn't have a problem on master because the lines in both Gemfiles (this one and manageiq/manageiq's Gemfile) are identical, this causes an issue on release branches because manageiq's gemfile says the new branch name (e.g. gaprindashvili), but then this file has a different branch name (e.g. master), and that blows up.  While we *could* just change it on the branch to the new release branch name, we don't want to have to remember to maintain that.
@simaishi Please review.
cc @aufi
=> manageiq-gems-pending is already from manageiq itself

app/models/manageiq/providers/openstack/inventory/parser/cloud_manager.rb
Make sure volume template has name
Fixes BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1510067
=> Make sure volume template has name

app/models/manageiq/providers/openstack/infra_manager/template.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1396218
OpenStack infra template cloning is not supported. With this fix
a flash message tells the user this is unsupported rather than
trying (and failing) to render the clone form.
=> BZ 1396218: don't attempt cloning of OpenStack infra templates

app/models/manageiq/providers/openstack/refresh_parser_common/helper_methods.rb
Some fog calls raise subclasses of `Fog::Errors::NotFound` instead of `Excon::Errors::NotFound`. This change allows `safe_call` (and by extension `safe_list`) to handle those cases.
This should fix issues with deleted flavors crashing refresh despite the catch, since `list_tenants_with_flavor_access` throws `Fog::Compute::OpenStack::NotFound`.
=> safe_call should catch Fog::Errors::NotFound

app/models/manageiq/providers/openstack/network_manager/floating_ip.rb
Fixes a problem described in https://bugzilla.redhat.com/show_bug.cgi?id=1490918 where leaving the optional floating ip field on the creation form blank resulted in an API error.
=> Remove floating_ip_address from the create request if it is blank

app/models/manageiq/providers/openstack/inventory/parser/cloud_manager.rb
Quotas were missing because ems_ref was being set to the tenant_id
which is not unique. Changed ems_ref to [tenant_id, quota name] to
match what was being used as lookup value to find_or_build.
Also removed collection of quotas that we are not modeling:
metadata items, injected files, server groups, and rbac policies.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1512641
=> Restore missing quotas in new graph-based collector

app/models/manageiq/providers/openstack/cloud_manager/cloud_resource_quota.rb, app/models/manageiq/providers/openstack/cloud_manager/refresh_parser.rb
Add missing quota information that were being displayed as unknown.
Disabled collection of metadata items, injected files, server groups,
and rbac policies quotas because we don't model them.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1504576
=> Fix missing quota calculations

app/models/manageiq/providers/openstack/network_manager/network_router.rb
Router can't be deleted if has assigned floating ips.
https://bugzilla.redhat.com/show_bug.cgi?id=1470754
=> add error message if FIP assigned to router

lib/manageiq/providers/openstack/legacy/openstack_handle/handle.rb
Should fix the bug reported in https://bugzilla.redhat.com/show_bug.cgi?id=1518182 by ensuring that `ssl_options` is always a hash when it gets passed into `try_connection`, so that the attempt to `merge` it doesn't fail.
=> Don't pass nil ssl_options to try_connection

app/models/manageiq/providers/openstack/cloud_manager/cloud_tenant.rb
Should fix the superficial bug in https://bugzilla.redhat.com/show_bug.cgi?id=1517531 that is obscuring the actual error from the Openstack API.
=> Include HelperMethods instead of extending

app/models/manageiq/providers/openstack/cloud_manager/cloud_volume.rb, spec/models/manageiq/providers/openstack/cloud_manager/cloud_volume_spec.rb
This handles an exception that would occur when attempting to delete
a volume that was already deleted from the provider, but the deletion
was not yet reflected in ManageIQ. The exception is now caught and
a nice error message is shown.
https://bugzilla.redhat.com/show_bug.cgi?id=1487234
=> Handle attempts to delete volumes that have already been deleted

app/models/manageiq/providers/openstack/inventory/parser/cloud_manager.rb
OpenStack volume can have empty name. This PR set name = id when name was empty
in order to allow user identify volume in Instance provisioning form.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1518637
=> Set VolumeTemplate name to ID if empty

app/models/manageiq/providers/openstack/helper_methods.rb
We need `:subject`, `:initiator` and `:cause` keys be a named keyword when
passing to Notification.create().
https://bugzilla.redhat.com/show_bug.cgi?id=1518640
=> Corrects handling of Notification params

lib/manageiq/providers/openstack/legacy/openstack_handle/handle.rb
Attempts to connect with disabled tenants generated misleading error messages,
skipping disabled tenants when obtaining connection to OpenStack.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1518625
=> Skip disabled tenants when connecting to OpenStack

app/models/manageiq/providers/openstack/infra_manager/ems_cluster.rb, app/models/manageiq/providers/openstack/infra_manager/host_service_group.rb, spec/models/manageiq/providers/openstack/infra_manager/host_service_group_spec.rb
Replace sql conditions with scopes.
=> Replace conditions with scope

app/models/manageiq/providers/openstack/cloud_manager.rb, app/models/manageiq/providers/openstack/infra_manager.rb, spec/models/manageiq/providers/openstack/cloud_manager_spec.rb, spec/models/manageiq/providers/openstack/infra_manager_spec.rb
For Service catalog items each provider has to now list the supported catalog types.
Needed for PR https://github.com/ManageIQ/manageiq/pull/16559
=> Added supported_catalog_types

app/models/manageiq/providers/openstack/cloud_manager/provision/cloning.rb
Since provisioning from OpenStack Volumes was enabled, situation when original
Volume template can be disconnected from EMS by refresher can happen and it
doesn't look to be possible fix it on OpenStack side.
This PR allows EMS lookup fallback to options[:src_ems_id] when getting EMS
from source object fails.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1518381
Links
----------------
* BZ https://bugzilla.redhat.com/show_bug.cgi?id=1518381
* PRs adding provision from OpenStack Volumes for better understanding https://github.com/ManageIQ/manageiq/pull/16066 and  https://github.com/ManageIQ/manageiq-providers-openstack/pull/104
Steps for Testing/QA
-------------------------------
Vm provision process from OpenStack Volume should pass even refresh of given provider runs faster than …
=> Fix Provisioning of disconnected VolumeTemplate

app/models/manageiq/providers/openstack/infra_manager.rb, spec/models/manageiq/providers/openstack/infra_manager_spec.rb
InfraProvider don't have relation to cloud_tenants - there was
created only empty method returning nil to preserve consitency - but on
some places is expected AR relation object.
For example screen add new subnet, there are listed network managers and
their parent manager's cloud_tenants but they can be infra manager whithout
cloud_tenants.
Such place, where was expected AR Relation object is here:
https://github.com/ManageIQ/manageiq-api/blob/master/app/controllers/api/subcollections/cloud_tenants.rb#L5
which was reached for example by this request:
http://localhost:3000/api/providers/:id/cloud_tenants but it fails later
when object has been infra manager and the method cloud_tenants_query_resource
was returning nil.
@miq-bot add_label graprindashvili/yes, bug
cc @gtanzillo 
@miq-bot …
=> Return empty AR relation instead of nil for ::InfraManager#cloud_tenants

app/models/manageiq/providers/openstack/inventory/parser/cloud_manager.rb
Hosts are stored in db with only hostname part of hostname.domain which
we can see in OpenStack.
That caused issue with matching VMs with Hosts when Cloud OpenStack had
Infra OpenStack related to it.
Solves https://bugzilla.redhat.com/show_bug.cgi?id=1528162
=> Use only hypervisor hostname to match infra host with cloud vm

app/models/manageiq/providers/openstack/inventory/parser/network_manager.rb, app/models/manageiq/providers/openstack/inventory_collection_default/network_manager.rb, app/models/manageiq/providers/openstack/network_manager/network_port.rb, spec/models/manageiq/providers/openstack/network_manager/cloud_subnet_refresh_spec.rb
Defaults the `network_router` field on subnets to `nil` during refresh. If the interface linking subnet to router still exists on the OSP side, the association will be restored while updating ports.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1449260
=> Ensure that subnets are dissociated from routers in the ManageIQ inventory when their interfaces are removed on the OSP side

app/models/manageiq/providers/openstack/cloud_manager/provision_workflow.rb, spec/models/manageiq/providers/openstack/cloud_manager/provision_workflow_spec.rb
PR https://github.com/ManageIQ/manageiq/pull/16811 and https://github.com/ManageIQ/manageiq/pull/16688 adds RBAC filtering to allowed_cloud_network base class but two of the providers don't support the allowed_ci method so for them we need to overwrite the allowed_cloud_networks, to just return allowed_cloud_networks. Which this does! (Per https://github.com/ManageIQ/manageiq/pull/16824#discussion_r161679886)
Fixes issue caused by fix of https://bugzilla.redhat.com/show_bug.cgi?id=1533277
(Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1535189)
https://github.com/ManageIQ/manageiq-providers-google/pull/41
=> Extend allowed_cloud_network for providers that don't support allowed_ci

app/models/manageiq/providers/openstack/cloud_manager.rb
This is a follow on PR from ManageIQ/manageiq#16802/
and ManageIQ/manageiq-api#279
=> Added keystone_v3_domain_id to api_allowed_attributes method

app/models/manageiq/providers/openstack/cloud_manager/provision_workflow.rb, spec/models/manageiq/providers/openstack/cloud_manager/provision_workflow_spec.rb
I messed up [here](https://github.com/ManageIQ/manageiq-providers-openstack/pull/197) should be reverted because the [logic in main](https://github.com/ManageIQ/manageiq/blob/master/app/models/manageiq/providers/cloud_manager/provision_workflow.rb#L98) is wrong. That else case should not include cloud_subnets: fixed in https://github.com/ManageIQ/manageiq/pull/16824. Per [comment](https://github.com/ManageIQ/manageiq/pull/16824/files#r161679886) we need to override this method in google and openstack because the availability zone to subnet relationship isn't set up yet. 
Fixes issue caused by fix of https://bugzilla.redhat.com/show_bug.cgi?id=1533277
(Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1535189)
https://github.com/ManageIQ/manageiq/pull/16824 …
=> Override az_zone_to_cloud_network in openstack prov

app/models/manageiq/providers/openstack/cloud_manager/refresh_parser.rb, app/models/manageiq/providers/openstack/inventory/parser/cloud_manager.rb, app/models/manageiq/providers/openstack/inventory/persister/cloud_manager.rb, app/models/manageiq/providers/openstack/inventory/persister/target_collection.rb, app/models/manageiq/providers/openstack/inventory_collection_default/cloud_manager.rb, app/models/manageiq/providers/openstack/refresh_parser_common/images.rb, spec/models/manageiq/providers/openstack/cloud_manager/refresh_spec_common.rb, spec/models/manageiq/providers/openstack/infra_manager/refresher_rhos_juno_spec.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1520565
Use os_distro and os_version properties on glance images to track operating system
information on templates and VMs.
=> BZ 1520565: Track guest OS for openstack images and VMs

spec/models/manageiq/providers/openstack/cloud_manager/provision_workflow_spec.rb
PR https://github.com/ManageIQ/manageiq/pull/16811 adds RBAC filtering to allowed_cloud_network base class and openstack needed specs around the fact that the cloud network list is NOT dependent on availability zone choice unlike azure and amazon. (Per https://github.com/ManageIQ/manageiq/pull/16824#discussion_r161679886)
Related bz links: 
https://bugzilla.redhat.com/show_bug.cgi?id=1533277
https://bugzilla.redhat.com/show_bug.cgi?id=1535189
=> Test az_to_cn method from super

app/models/manageiq/providers/openstack/cloud_manager.rb, app/models/manageiq/providers/openstack/cloud_manager/cloud_tenant.rb, app/models/manageiq/providers/openstack/cloud_manager/orchestration_stack.rb, app/models/manageiq/providers/openstack/cloud_manager/orchestration_template.rb, app/models/manageiq/providers/openstack/cloud_manager/vm.rb, app/models/manageiq/providers/openstack/cloud_manager/vnfd_template.rb, app/models/manageiq/providers/openstack/infra_manager.rb, app/models/manageiq/providers/openstack/infra_manager/host.rb, app/models/manageiq/providers/openstack/infra_manager/orchestration_stack.rb, app/models/manageiq/providers/openstack/network_manager.rb, app/models/manageiq/providers/openstack/network_manager/cloud_network.rb, app/models/manageiq/providers/openstack/network_manager/cloud_network/private.rb, app/models/manageiq/providers/openstack/network_manager/cloud_network/public.rb, app/models/manageiq/providers/openstack/network_manager/cloud_subnet.rb, app/models/manageiq/providers/openstack/network_manager/floating_ip.rb, app/models/manageiq/providers/openstack/network_manager/network_port.rb, app/models/manageiq/providers/openstack/network_manager/network_router.rb, app/models/manageiq/providers/openstack/network_manager/security_group.rb
This is a continuation of the work started in https://github.com/ManageIQ/manageiq/pull/16596 where we want to migrate display model names from locale/en.yml into particular models, where we'll use standard gettext. Main goal here is to make this one aspect of our application pluggable.
Core PR: https://github.com/ManageIQ/manageiq/pull/16836
=> Migrate model display names from locale/en.yml to plugin

app/models/manageiq/providers/openstack/cloud_manager.rb, spec/models/manageiq/providers/openstack/infra_manager_spec.rb
Destroying child_managers is orchestrated by the parent and destroying
them prematurely leads to issues when the endpoints are shared between
the two managers.
Example failure: https://travis-ci.org/ManageIQ/manageiq-providers-openstack/jobs/332446792#L2079-L2091
Depends: https://github.com/ManageIQ/manageiq/pull/16871
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1538232
=> Don't dependent => destroy child_managers

app/models/manageiq/providers/openstack/provider.rb, spec/models/manageiq/providers/openstack/cloud_manager_spec.rb, spec/models/manageiq/providers/openstack/infra_manager_spec.rb
In the OpenStack provider, the Provider instance is only tightly coupled
to the InfraManager.  That is, when the InfraManager is created, then
the Provider is created and vice-versa, when the InfraManager is
destroyed, we need to destroy the Provider.  The CloudManager objects
associated to that Provider should *not* be destroyed, and only need to
be nullified.  For other Providers, the Provider instance is what is
destroyed, so by default the orchestrated destroy destroys all of its
managers, but we here don't want that to happen, so we are bypassing.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1538232
@Ladas @aufi Please review
cc @agrare @jameswnl
=> Bypass the superclass orchestrated destroy for this Provider.

app/models/manageiq/providers/openstack/cloud_manager/provision_workflow.rb
Part of https://github.com/ManageIQ/manageiq/pull/16898.
https://bugzilla.redhat.com/show_bug.cgi?id=1538696
@miq-bot add_label bug, gaprindashvili/yes
=> Add back missing IP address range in Virtual Private Cloud name.

app/models/manageiq/providers/openstack/inventory/collector/target_collection.rb, lib/manageiq/providers/openstack/legacy/openstack_handle/identity_delegate.rb
Vm targeted refresh queued related Cloud Tenant refresh, that could fail due to
keystone v3 backend in fog or an issue in fog/openstack method get_project_by_id.
Queueing CloudTenant doesn't seem to be actually needed - disabled now and we should
make a cleanup in ongoing PR.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1538741
=> Fix disable CloudTenant Vm targeted refresh

app/models/manageiq/providers/openstack/inventory/collector.rb, app/models/manageiq/providers/openstack/inventory/parser.rb, app/models/manageiq/providers/openstack/inventory/persister.rb
This require shouldn't be necessary and causes an exception.
=> Don't require CinderManager in inventory classes

lib/manageiq-providers-openstack.rb
The network discovery probe's class is declared with `autoload`. The autoload belongs to the provider too.
This is part of https://github.com/ManageIQ/manageiq-network_discovery/issues/8
=> autoload move

app/models/manageiq/providers/openstack/inventory/parser/cloud_manager.rb, app/models/manageiq/providers/openstack/inventory/parser/network_manager.rb, app/models/manageiq/providers/openstack/inventory/parser/storage_manager/cinder_manager.rb, app/models/manageiq/providers/openstack/inventory/persister/network_manager.rb, spec/models/manageiq/providers/openstack/infra_manager/refresher_rhos_juno_spec.rb
Use proper nested references in parser. Adding nested
lazy_finds to correctly model a complex link.
Fixes  https://github.com/ManageIQ/manageiq-providers-openstack/issues/164
=> Use proper nested references in parser

config/settings.yml, lib/manageiq/providers/openstack/legacy/events/openstack_rabbit_event_monitor.rb
We need to provide different vhost that default '/'. This commit adds the functionality to set it via Settings. 
It was already discussed @aufi.
=> Add configurable vhost to AMQP monitor

app/models/manageiq/providers/openstack/network_manager/cloud_network.rb
When creating network, add proper error message if network type is not supported by provider.
Fixes [link](https://bugzilla.redhat.com/show_bug.cgi?id=1540692)
=> Add proper error message if network type not supported

app/models/manageiq/providers/openstack/cloud_manager/cloud_volume.rb
BZ 1524309: handle "volume doesn't exist" situation in raw_delete_volume:
https://bugzilla.redhat.com/show_bug.cgi?id=1524309
=> Bug 1524309 - Repetitive storage volume deletion gives unexpected error`

app/models/manageiq/providers/openstack/identity_sync_mixin.rb, spec/models/manageiq/providers/openstack/identity_sync_mixin_spec.rb
Selected roles are saved as provider custom attributes.
If roles are changed between different syncs, user memberships from
previously selected roles should be removed.
=> Store selected user sync roles as custom attributes.

app/models/manageiq/providers/openstack/cloud_manager/provision.rb, app/models/manageiq/providers/openstack/cloud_manager/provision/cloning.rb, app/models/manageiq/providers/openstack/cloud_manager/provision/options_helper.rb
Call new cloud_tenant helper method to avoid provision error.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1532244
Provision error:  
[----] I, [2018-01-31T13:04:42.560968 #4325:f61134]  INFO -- : Q-task_id([miq_provision_1000000000024]) Starting Phase <provision_error>
[----] E, [2018-01-31T13:04:42.629955 #4325:f61134] ERROR -- : Q-task_id([miq_provision_1000000000024]) MIQ(ManageIQ::Providers::Openstack::CloudManager::Provision#provision_error) [[NoMethodError]: undefined method `[]' for nil:NilClass] encountered during phase [start_clone_task]
[----] E, [2018-01-31T13:04:42.630183 #4325:f61134] ERROR -- : Q-task_id([miq_provision_1000000000024]) /var/www/miq/vmdb/app/models/mixins/provider_object_mixin.rb:29:in `connection_source' …
=> Fix Service Provisioning cloud_tenant issue

app/models/manageiq/providers/openstack/discovery.rb, spec/models/manageiq/providers/openstack/discovery_spec.rb
https://github.com/ManageIQ/manageiq/pull/16994
Add missing test for the probe method.
=> Update client to use renamed NetworkDiscovery

spec/models/manageiq/providers/openstack/infra_manager/event_parser_spec.rb
Fixes the build by replacing references to a deprecated custom matcher that was removed in https://github.com/ManageIQ/manageiq/pull/17021
=> Replace use of custom have_attributes matcher with "include"

app/models/manageiq/providers/openstack/cloud_manager/template.rb
Added missing method `delete_image_queue` for templates in order to use it in API `delete` action
https://github.com/ManageIQ/manageiq-api/pull/328
=> Add delete_queue method for Template

app/models/manageiq/providers/openstack/network_manager/event_target_parser.rb, spec/models/manageiq/providers/openstack/network_manager/event_target_parser_spec.rb
The network event target parser was using the wrong association names for some objects, causing targeted refresh for those objects to be skipped.
https://bugzilla.redhat.com/show_bug.cgi?id=1519460
=> Correct network event target associations

app/models/manageiq/providers/openstack/cloud_manager/provision.rb, app/models/manageiq/providers/openstack/cloud_manager/provision/cloning.rb
Parse messages from fog responses and pull fault messages
from incomplete instances.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1549846
=> Improve provisioning failure error messages

app/models/manageiq/providers/openstack/cloud_manager/provision_workflow.rb, spec/models/manageiq/providers/openstack/cloud_manager/provision_workflow_spec.rb
Add eligible_for_vm_provisioning method for networks. Network requires a subnet in order to be used for provisioning.
This method is needed for this [PR](https://github.com/ManageIQ/manageiq/pull/17055) and should fix [BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1541308)
=> Filter openstack networks without subnets

app/models/manageiq/providers/openstack/cloud_manager.rb
Check if the cinder and swift services are actually present before
checking the names and returning them.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1458959
along with https://github.com/ManageIQ/manageiq/pull/17067.
Order of merging is irrelevant.  Related PR was https://github.com/ManageIQ/manageiq/pull/16922
@roliveri @hsong-rh please review and merge when appropriate.
=> Dont return Storage Services if They arent present

app/models/manageiq/providers/openstack/inventory/parser/network_manager.rb
The parent subnet relationship is using the wrong attribute. "vsd_managed" contains a boolean that indicates whether a parent subnet is present, and "vsd_id" contains its id. This PR corrects parent subnet collection.
https://bugzilla.redhat.com/show_bug.cgi?id=1549117
@alexander-demichev 
@aufi
=> Fix parent subnet relationship

app/models/manageiq/providers/openstack/cloud_manager/event_parser.rb, app/models/manageiq/providers/openstack/infra_manager/event_parser.rb, app/models/manageiq/providers/openstack/network_manager/event_parser.rb
Event payload received from OpenStack could have nil content which
resulted in failures in code assigning Event to inventory.
Defaulting empty hash for payload to avoid it.
Should fix https://bugzilla.redhat.com/show_bug.cgi?id=1519887
=> Default Event payload to empty Hash

app/models/manageiq/providers/openstack/base_metrics_capture.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1545322
Check for nil before attempting to generate a resource ID based on ems_ref
=> BZ1545322: metrics capture shouldn't fail on nil NetworkPort ems_ref

app/models/manageiq/providers/openstack/helper_methods.rb
Addresses the error parsing issue mentioned in https://bugzilla.redhat.com/show_bug.cgi?id=1562065
=> Fallback to generic error parsing if neutron-specific parsing fails

app/models/manageiq/providers/openstack/helper_methods.rb
Create/Update/Delete Cloud Network caused unfriendly message when provider unavailable (fix)
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1510769
Cc @Ladas 
In **Networks** -> **Networks**:
1. Click **Configure** / **Add a new Cloud Network**
2. Choose Network manager of unavailable provider (_OpenStack / Ovirt only _)
3. Fill required fields and click **Add**
Actual results:
Unfriendly error message. ("undefined method `response' for <...> Did you mean? respond_to?")
Expected results:
Message should be friendly.
=> Fixes unfriendly message when adding network for unavailable provider

config/settings.yml, lib/manageiq/providers/openstack/legacy/openstack_handle/metric_delegate.rb
ManageIQ counts with default "minimal" granularity for collecting Metrics via
OpenStack Gnocchi service. This PR makes the default granularity an option in
Settings which allows configure it on customer side.
Adjusting this should resolve Metric NotFound errors caused by not matching
granularity.
Solves https://bugzilla.redhat.com/show_bug.cgi?id=1529449
=> Make Gnocchi default granularity configurable in Settings

lib/manageiq/providers/openstack/legacy/openstack_handle/network_delegate.rb
Quotas from Neutron don't seem to contain an 'id' field like from Nova, so the current collection fails to gather the networking quotas correctly.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1390456
=> Use the correct id when collecting quotas from Neutron

app/models/manageiq/providers/openstack/manager_mixin.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1545520
=> translate_exceptions: Parse errors out of fog responses

app/models/manageiq/providers/openstack/cloud_manager/cloud_tenant.rb
It creates UI notifications, when deleting CloudTenant.
Depends on https://github.com/ManageIQ/manageiq/pull/17011
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1448683
=> Add delete notifications for CloudTenant

app/models/manageiq/providers/openstack/cloud_manager/cloud_resource_quota.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1506987
For cloud resource quota reporting, per_volume_gigabytes_used is
missing, causing -1 to be shown instead of a real value.
The per_volume_gigabytes quota parameter is not a true quota limit,
since it's not an aggregate across volumes but a per-volume limit.
However, since OpenStack defines it as a quota param along with the
aggregate values, MIQ treats it in the same way as the other
parameters.
In this case, we're reporting the size of the largest volume, since
the limit is a per-volume limit rather than an aggregate one.
=> Bug 1506987: per_volume_gigabytes_used definition is missing

app/models/manageiq/providers/openstack/inventory/parser/cloud_manager.rb, spec/models/manageiq/providers/openstack/openstack_stubs.rb, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_legacy_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_legacy_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_network_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_stack_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_tenant_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_vm_targeted_refresh.yml
When the CloudManager refreshes, it removes from the inventory any Disks that were only added by the CinderManager as part of attaching Volumes to VMs since the CloudManager doesn't find them while collecting inventory. As a result, Volumes will have correct statuses but incorrect numbers of attachments, leading to confusing user experience and various UI actions failing.
This patch causes the CloudManager to be aware of VM volume attachments so that the associations are not broken between Cloud and Cinder refreshes.
This is a solution for https://bugzilla.redhat.com/show_bug.cgi?id=1544344
Depends on https://github.com/ManageIQ/manageiq-providers-openstack/pull/242
=> Don't lose VM volume attachments when refreshing the cloud inventory

app/models/manageiq/providers/openstack/builder.rb, app/models/manageiq/providers/openstack/inventory/collector.rb, app/models/manageiq/providers/openstack/inventory/collector/cinder_manager.rb, app/models/manageiq/providers/openstack/inventory/parser.rb, app/models/manageiq/providers/openstack/inventory/parser/cinder_manager.rb, app/models/manageiq/providers/openstack/inventory/persister.rb, app/models/manageiq/providers/openstack/inventory/persister/cinder_manager.rb
Moves the CinderManager inventory classes out from being nested under StorageManager so that `ManagerRefresh::Inventory.persister_class_for` and `ManagerRefresh::Inventory.parser_class_for` can find them.
=> Move CinderManager inventory classes

lib/manageiq/providers/openstack/legacy/openstack_handle/handle.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1573893
raw_connect_try_ssl modifies the opts hash (pulling out :ssl_options and then
using it. This means that if raw_connect_try_ssl is called twice with the
same opts hash, the second time fails because of the side effect of the first
call. With this change, the method works on a copy of the hash rather than
the original
=> bz1573893: duplicate opts hash before modifying in raw_connect_try_ssl

app/models/manageiq/providers/openstack/infra_manager/refresh_worker.rb, spec/models/manageiq/providers/openstack/infra_manager/refresh_worker_spec.rb
When the CloudManager's refresh queues were consolidated,
the individual NetworkManager refresh worker was removed.
However, the InfraManager's queues were not combined at
the same time, resulting in Infra network refresh events
not being picked up. This commit ensures that the Infra
Manager's refresh worker picks up queued refreshes for
its child managers as well.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1572760
=> Combine InfraManager and child manager refresh queues

app/models/manageiq/providers/openstack/inventory/persister/target_collection.rb, lib/vcr_recorder.rb, spec/models/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_spec.rb, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_port_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_router_targeted_refresh.yml
Targeted refresh for newly created routers resulted in the routers not being properly associated with their parent manager due to missing builder params. This PR fixes that.
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/3918
=> Fix targeted refresh builder params for network objects

app/models/manageiq/providers/openstack/cloud_manager/provision_workflow.rb, spec/models/manageiq/providers/openstack/cloud_manager/provision_workflow_spec.rb
This PR add default volume size value for instance provisioning in case if only name is specified. A placeholder with warning will be placed in UI field.
https://bugzilla.redhat.com/show_bug.cgi?id=1417215
=> Default volume size value in provisioning

app/models/manageiq/providers/openstack/helper_methods.rb
Handling HTML error responses from undercloud
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1566570
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1510769
---
Steps to reproduce:
> In our Setup we usually use a deployment of 3 controllers and 2 compute nodes.
> You need to login from undercloud to each controller and stop below services:
```
neutron-dhcp-agent.service                                           
neutron-openvswitch-agent.service                                               
neutron-server.service
```
In **Networks -> Networks**:
1. Click **Configure** / **Add a new Cloud Network**
2. Choose Network manager of unavailable provider (_OpenStack_ / _Ovirt_ only)
3. Fill required fields and click **Add**
---
**Actual results**: 
`unexpected token at '<html><body><h1>503 …
=> Friendly error message for HTTP 503

app/models/manageiq/providers/openstack/inventory/persister/definitions/cloud_collections.rb, app/models/manageiq/providers/openstack/inventory/persister/definitions/network_collections.rb, app/models/manageiq/providers/openstack/inventory/persister/definitions/storage_collections.rb, app/models/manageiq/providers/openstack/inventory/persister/definitions/utils.rb
Optimizations and simplification of InventoryCollection definitions
**Issue**: https://github.com/ManageIQ/manageiq/issues/17396
- ((**depends on**): https://github.com/ManageIQ/manageiq/pull/17621
What is possible is moved to core
=> Persister: optimized InventoryCollection definitions

manageiq-providers-openstack.gemspec, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_network_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_vm_targeted_refresh.yml
Also fixes vcr cassettes to work with fog-openstack 0.1.27 because of redudant `/` in Compute which was fixed by https://github.com/fog/fog-openstack/commit/19fff350b3d5af3f7108da7bbc4bc8b8463aebfa
Required to support:
https://bugzilla.redhat.com/show_bug.cgi?id=1596320
https://bugzilla.redhat.com/show_bug.cgi?id=1589766
=> Bump fog-openstack to version 0.1.27

app/models/manageiq/providers/openstack/cloud_manager/provision_workflow.rb
Align with OpenStack behaviour when building a new instance and be able to choose a flavor with disk size of 0. The disk size is then determined by the base image build definition.
https://bugzilla.redhat.com/show_bug.cgi?id=1540588
=> Instances workflow: Allow flavors with disk size of 0

manageiq-providers-openstack.gemspec
Backport of https://github.com/ManageIQ/manageiq-providers-openstack/pull/317
https://bugzilla.redhat.com/show_bug.cgi?id=1603022
https://bugzilla.redhat.com/show_bug.cgi?id=1589766
=> [Gaprindashvili] fog openstack bump to version 0.1.27

app/decorators/manageiq/providers/openstack/cloud_manager/template_decorator.rb
Add a UI decorator for template. Method ```provisioning_volume_size_tooltip ``` returns message that will be displayed in instance provisioning.
=> Add template decorator

app/models/manageiq/providers/openstack/cloud_manager.rb
This should prevent requiring hostname during deletion.
https://bugzilla.redhat.com/show_bug.cgi?id=1590204
=> Require hostname if provider is enabled

app/models/manageiq/providers/openstack/network_manager/network_router.rb
Added notifications for deleting Network Router. 
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1518734
Depends on https://github.com/ManageIQ/manageiq/pull/17514
=> Add notifications for Router delete

app/models/manageiq/providers/openstack/refresh_parser_common/helper_methods.rb
Should fix https://bugzilla.redhat.com/show_bug.cgi?id=1611848
=> Catch Bad Request responses in safe_call

app/models/manageiq/providers/openstack/cloud_manager/event_target_parser.rb, app/models/manageiq/providers/openstack/inventory/collector/target_collection.rb, app/models/manageiq/providers/openstack/inventory/persister/definitions/cloud_collections.rb, app/models/manageiq/providers/openstack/inventory/persister/definitions/storage_collections.rb, app/models/manageiq/providers/openstack/storage_manager/cinder_manager/event_target_parser.rb, spec/models/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_spec.rb, spec/models/manageiq/providers/openstack/cloud_manager/stubbed_refresher_spec.rb, spec/models/manageiq/providers/openstack/openstack_stubs.rb, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_legacy_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_legacy_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_network_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_port_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_router_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_stack_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_tenant_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_vm_targeted_refresh.yml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1596058 in combination with https://github.com/ManageIQ/manageiq-content/pull/371 and https://github.com/ManageIQ/manageiq-content/pull/372
=> Targeted refresh workaround for events that don't identify objects

app/models/manageiq/providers/openstack/inventory/collector.rb, app/models/manageiq/providers/openstack/inventory/collector/cloud_manager.rb, app/models/manageiq/providers/openstack/inventory/collector/network_manager.rb, app/models/manageiq/providers/openstack/inventory/collector/target_collection.rb
Hi everyone,
This PR resolves an issue I discovered where we will query Heat more than once per tenant during the NetworkManager refresh in environments where there are no orchestration stacks.
Where there are no orchestration stacks an empty list is always returned, which causes .any? to return False, and so doesn't stop another round of queries to Heat the next time orchestration_stacks is called.
The number of queries scales according to the number of cloud networks and security groups in the environment, as we attempt to match up their parent stack by calling orchestration_stacks...which triggers yet another batch of queries to Heat, one per tenant.
I did see a possible opportunity to adjust the initialisers for the other lists in Collector to also use the same logic, but given I'm …
=> Use nil as initialiser for @orchestration_stacks to prevent looping.

app/models/manageiq/providers/openstack/inventory/parser/cloud_manager.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1513086
For OpenStack cloud, cpu_cores_per_socket was always set to 1 in the legacy refresh_parser
since OpenStack flavors only have a single "number of CPUs" param. The new inventory
parser was not setting this param at all, though, leaving it as nil.
=> bug 1513086: add cores per socket to OpenStack cloud inventory parser

app/models/manageiq/providers/openstack/cloud_manager/flavor.rb, spec/models/manageiq/providers/openstack/cloud_manager/flavor_spec.rb
Set tenant access when creating non public flavor. After a non-public flavor is created add tenant access. Array with tenants comes with `create_options ` from UI.
https://bugzilla.redhat.com/show_bug.cgi?id=1609564
@aufi
=> Set tenant access when creating non public flavor

app/models/manageiq/providers/openstack/cloud_manager/cloud_tenant.rb, spec/models/manageiq/providers/openstack/cloud_manager/cloud_tenant_spec.rb
Adds a `default_security_group` instance method to CloudTenant that returns a security group named `default` if that CloudTenant has one, or else returns the security group with the highest population of VMs.
=> Add 'default_security_group' method to CloudTenant

lib/manageiq/providers/openstack/legacy/openstack_handle/identity_delegate.rb
In order to connect from MIQ to OpenStack, MIQ lists projects
accessible for current User.
OpenStack provides list of all projects accessible for the User. But
MIQ allows to specify domain_id in Add provider form, so it is
expected see only project within such domain.
Adding filtering of projects available for the user by domain_id.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1593923
=> Filter Keystone Projects by domain_id

app/models/manageiq/providers/openstack/cloud_manager/provision_workflow.rb, spec/models/manageiq/providers/openstack/cloud_manager/provision_workflow_spec.rb
Volumes that don't have name should be filtered from provisioning. When there is no name infinite loop may appear, so I added `index` variable.
https://bugzilla.redhat.com/show_bug.cgi?id=1625970
@aufi @mansam
=> Use empty name for volume if only size provided

app/models/manageiq/providers/openstack/cloud_manager/cloud_tenant.rb
The `virtual_has_one` for `default_security_group` makes `default_security_group ` visible in the `cloud_tenants` API as shown below -
```
{
"href": "http://localhost:3000/api/cloud_tenants/8",
"id": "8",
"name": "Massachusetts",
"description": "",
"enabled": true,
"ems_ref": "52cf9d53e2a84e21b62e6c815157c59a",
"ems_id": "7",
"created_at": "2017-11-07T20:27:52Z",
"updated_at": "2017-11-07T20:27:52Z",
"type": "ManageIQ::Providers::Openstack::CloudManager::CloudTenant",
"parent_id": null,
"default_security_group": {
"id": "117",
"name": "default",
"description": "Default security group",
"type": "ManageIQ::Providers::Openstack::NetworkManager::SecurityGroup",
"ems_id": "8",
"ems_ref": "e8b2d278-0968-4324-a027-6157c66ecbc6",
"cloud_network_id": null,
"cloud_tenant_id": "8", …
```
=> Make `default_security_group` visible in the API

app/models/manageiq/providers/openstack/inventory/collector.rb, app/models/manageiq/providers/openstack/inventory/collector/storage_manager.rb, app/models/manageiq/providers/openstack/inventory/parser.rb, app/models/manageiq/providers/openstack/inventory/parser/storage_manager.rb, app/models/manageiq/providers/openstack/inventory/persister.rb, app/models/manageiq/providers/openstack/inventory/persister/storage_manager.rb
One of the recent inventory refactor PRs moved the location of the CinderManager inventory modules, which causes problems in the console and in other situations because the `require_nested :CinderManager` calls don't work. This adds modules to fix the import path and updates the `require_nested` call.
=> Add StorageManager modules to fix CinderManager import paths

app/models/manageiq/providers/openstack/inventory/parser/storage_manager/cinder_manager.rb
Adds missing behavior that we had in the old refresh parser.
=> Use UUID if volume name is missing

app/models/manageiq/providers/openstack/inventory/collector/cloud_manager.rb, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_legacy_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_legacy_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_network_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_port_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_router_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_stack_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_tenant_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_vm_targeted_refresh.yml
Adds missing `openstack_admin?` to the Cloud Manager's volume snapshot templates collection.
=> Pass openstack_admin? flag to volume snapshot template collection

app/models/manageiq/providers/openstack/cloud_manager/cloud_tenant.rb
The changes in this PR allow us to gain direct attribute access to `cloud_volume_types` via the `cloud_tenants` API, as shown below - 
```
api/cloud_tenants/20000000000001?attributes=cloud_volume_types
```
```
{
"href": "http://0.0.0.0:8080/api/cloud_tenants/20000000000001",
"id": "20000000000001",
"name": "fdupont-prj-1",
"description": "",
"enabled": true,
"ems_ref": "0898f6eef46c4f17a79db2f9d73a3a40",
"ems_id": "20000000000006",
"created_at": "2018-09-26T22:26:37Z",
"updated_at": "2018-09-26T22:26:37Z",
"type": "ManageIQ::Providers::Openstack::CloudManager::CloudTenant",
"parent_id": null,
"cloud_volume_types": [
{
"href": "http://0.0.0.0:8080/api/cloud_volume_types/20000000000001",
"id": "20000000000001",
"description": null,
"name": "default",
"type": …
```
=> Direct attribute access for `cloud_volume_types` via cloud_tenants API

app/models/manageiq/providers/openstack/network_manager/cloud_network.rb
Format error when creating cloud "flat" network if physical network is in use
https://bugzilla.redhat.com/show_bug.cgi?id=1635617
@aufi @mansam
=> Format error when physical network is in use

app/models/manageiq/providers/openstack/cloud_manager/template.rb, spec/models/manageiq/providers/openstack/cloud_manager/template_spec.rb
Added filtering in `options` from unnecessary data, which doesn't belong to image attributes
=> Add filtering of image attributes

app/models/manageiq/providers/openstack/infra_manager.rb, app/models/manageiq/providers/openstack/manager_mixin.rb
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1538825
For OpenStack infra providers, validate credentials also checks for Baremetal service.
=> bz 1538825: For OpenStack infra validation, validate presence of Ironic

app/models/manageiq/providers/openstack/manager_mixin.rb
Splits `#raw_connect` to target separately AMQP availability and ems default connect.
https://bugzilla.redhat.com/show_bug.cgi?id=1593663
=> New Cloud provider: Fix event creds validation for AMQP

lib/manageiq/providers/openstack/legacy/openstack_handle/handle.rb, lib/manageiq/providers/openstack/legacy/openstack_handle/handled_list.rb, lib/manageiq/providers/openstack/legacy/openstack_handle/identity_delegate.rb, manageiq-providers-openstack.gemspec, spec/legacy/openstack_handle/handle_spec.rb, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_legacy_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_legacy_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_network_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_port_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_router_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_stack_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_tenant_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_vm_targeted_refresh.yml
Changes necessary to use fog-openstack supporting "version less" endpoint (including identity) and which avoid tempering with URL path.
Tested: Cloud/Infra on Gaprindashvili and master
Requires https://github.com/ManageIQ/manageiq-gems-pending/pull/386
=> A fog-openstack with a more "version less" approach

manageiq-providers-openstack.gemspec
Brings in https://github.com/fog/fog-openstack/pull/458 and https://github.com/fog/fog-openstack/pull/459
=> Bump fog-openstack to v0.3.8

manageiq-providers-openstack.gemspec
https://bugzilla.redhat.com/show_bug.cgi?id=1624840
https://bugzilla.redhat.com/show_bug.cgi?id=1608230
=> [HAMMER] Bumps fog-openstack to v0.1.28

app/models/manageiq/providers/openstack/infra_manager/refresh_parser.rb
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1475616
This commit fixes the refresh parser for disks attached to infra
nodes so that all disks associated with the node will be saved
rather than only the last one.
=> bug 1475616: Save all disks from infra host on refresh

app/models/manageiq/providers/openstack/inventory/collector/target_collection.rb, lib/vcr_recorder.rb, spec/models/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_spec.rb, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_legacy_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_legacy_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_network_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_port_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_router_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_tenant_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_vm_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_volume_targeted_refresh.yml
If a volume that is attached to one or more VMs is subject to targeted refresh, but one of the VMs it is attached to hasn't yet been pulled into the inventory, then building the association between the volume and its attachments could fail. This PR collects any attached VMs as part of targeted refresh for a volume.
=> When doing targeted refresh of a volume, refresh any attached VMs

manageiq-providers-openstack.gemspec
fog-openstack v0.1.29 has the back port for instance evacuation for Nova 1.24+:
https://bugzilla.redhat.com/show_bug.cgi?id=1644613
=> Bump fog-openstack to v0.3.9

manageiq-providers-openstack.gemspec
fog-openstack v0.1.29 has the back port for instance evacuation for Nova 1.24+:
https://bugzilla.redhat.com/show_bug.cgi?id=1644613
=> [HAMMER] Bump fog-openstack to v0.1.29

app/models/manageiq/providers/openstack/manager_mixin.rb, lib/manageiq/providers/openstack/legacy/events/openstack_rabbit_event_monitor.rb, spec/legacy/events/openstack_rabbit_event_monitor_spec.rb, spec/models/manageiq/providers/openstack/cloud_manager_spec.rb
This PR adds support for multiple amqp endpoints. Currently, it's possible to use only one endpoint when adding a provider. If amqp server is not available CF should switch to another. Amqp is out of openstack HA proxy, so there is no other way to handle server fails. I replaced raising exceptions with returning false in case of fail for being able to iterate through hostnames.
We would need UI for this.
@aufi @mansam 
https://bugzilla.redhat.com/show_bug.cgi?id=1595558
=> Add support for multiple amqp endpoints

app/models/manageiq/providers/openstack/cloud_manager.rb, spec/models/manageiq/providers/openstack/cloud_manager_spec.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1445717 by kicking off a refresh when the overcloud is saved.
Fixed problems with https://github.com/ManageIQ/manageiq-providers-openstack/pull/389
=> Refresh an attached undercloud when saving changes to an overcloud

app/models/manageiq/providers/openstack/cloud_manager/orchestration_template.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1642594
https://github.com/ManageIQ/manageiq/pull/18202 removed the tenant selection, which need to be added in openstack provider.
Depends on https://github.com/ManageIQ/manageiq/pull/18202.
=> Service dialog for orchestration template needs tenant selection

app/models/manageiq/providers/openstack/infra_manager/event_parser.rb, app/models/manageiq/providers/openstack/infra_manager/host.rb, app/models/manageiq/providers/openstack/infra_manager/refresher.rb, spec/models/manageiq/providers/openstack/infra_manager/host_spec.rb
After creating host check if `compute.instance.create.end` event exists and assign host to it.
I don't know if there is a better way to assign a host, querying all events and then selecting hosts doesn't look very efficient, but I didn't came up with something better.
@mansam  Can you review it? :)
https://bugzilla.redhat.com/show_bug.cgi?id=1584770
=> Check if host create event exists and assign host to it

manageiq-providers-openstack.gemspec
The `parallel` gem is apparently only normally pulled in via the `parallel_tests` gem during development. This means the tests were passing, but it was causing failures in an appliance environment. This PR makes the dependency explicit.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1652574
=> Add explicit runtime dependency on the "parallel" gem

lib/manageiq/providers/openstack/legacy/events/openstack_ceilometer_event_monitor.rb
It appears that by default Panko events are only returned for a single tenant at a time. There's a query parameter that returns all events for an admin user, which this PR enables. https://docs.openstack.org/panko/latest/webapi/v2.html
@fdupont-redhat
=> Collect Panko events for all tenants.

config/settings.yml
This is a QoL improvement, should not be necessary for any functionality.
=> Add a default parallel thread limit to the settings yaml

app/models/manageiq/providers/openstack/cloud_manager/vm.rb, spec/models/manageiq/providers/openstack/cloud_manager/vm_spec.rb
This sets supports :conversion_host to the Vm model.
The main purpose for this is for the ManageIQ REST API, where support for conversion_host will be checked before attempting to enable or disable the resource.
Part of the V2V effort.
=> Add supports_conversion_host to Vm

app/models/manageiq/providers/openstack/cloud_manager/cloud_volume.rb, spec/models/manageiq/providers/openstack/cloud_manager/cloud_volume_spec.rb
This PR updates the Volume -> Attach to Instance form to exclude instances that are already attached to the selected volume.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1653062
=> Exclude already attached VMs from the volume attachment form

app/models/manageiq/providers/openstack/cloud_manager/cloud_volume_backup.rb
Fixes `raw_restore` to better reflect the Cinder API's ability to restore backups to brand new volumes.
Depends on core PR and a new fog-openstack release including https://github.com/fog/fog-openstack/pull/419
https://bugzilla.redhat.com/show_bug.cgi?id=1514970
=> Take an optional "name" parameter when restoring volume backups

app/models/manageiq/providers/openstack/inventory/persister.rb
The shared_options were duplicated from the base persister
=> Remove duplicated persister shared_options

app/models/manageiq/providers/openstack/inventory/collector/target_collection.rb, spec/models/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_spec.rb, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_legacy_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_legacy_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_network_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_port_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_router_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_stack_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_tenant_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_vm_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_volume_targeted_refresh.yml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1662126 by ensuring that the reference cache is refreshed before collecting tenants during a targeted refresh.
=>  Targeted refresh: Collect tenant ems references last

app/models/manageiq/providers/openstack/inventory/parser/cloud_manager.rb, spec/models/manageiq/providers/openstack/openstack_stubs.rb
Get tenant for stack from parameters, not from service, because service seems to always be admin
@aufi @mansam 
https://bugzilla.redhat.com/show_bug.cgi?id=1597125
=> Get tenant for stack from parameters

config/settings.yml, lib/manageiq/providers/openstack/legacy/events/openstack_ceilometer_event_monitor.rb, spec/models/manageiq/providers/openstack/cloud_manager/event_target_parser_spec.rb
Adds a setting to specify the number of seconds prior to the last received event to query Panko for events, so as to help catch events that may have arrived in Panko out of order.
=> Read back to catch events that may have reached Panko out of order

app/models/manageiq/providers/openstack/infra_manager.rb, app/models/manageiq/providers/openstack/infra_manager/refresh_parser.rb
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1664888
This commit changes the validation to warn but not fail for
infra providers without Ironic. In addition, refresh no longer
fails if ironic is missing -- it just logs a warning instead.
=> Bug 1664888: Warn, but still allow infra without ironic

app/models/manageiq/providers/openstack/cloud_manager/conversion_host.rb, app/models/manageiq/providers/openstack/cloud_manager/service_template_transformation_plan.rb
For the V2V effort, we will want subclasses for both the ConversionHost and ServiceTemplateTransformationPlan models. For now these are just stubs, but the plan is to add additional logic in the future.
For the ConversionHost model, this will likely contain provider-specific authentication code. At the moment, we have some ugly provider-specific code baked into the core ConversionHost model, which I would like to polymorphosize.
For the ServiceTemplateTransformationPlan model, this will contain provider-specific mapping validation code.
Both underlying tables (conversion_hosts and service_templates) are already setup for STI.
See also: https://github.com/ManageIQ/manageiq-providers-ovirt/pull/339
=> Add ConversionHost and ServiceTemplateTransformationPlan subclasses

app/models/manageiq/providers/openstack/cloud_manager/provision/configuration.rb, app/models/manageiq/providers/openstack/cloud_manager/provision/options_helper.rb, app/models/manageiq/providers/openstack/cloud_manager/provision_workflow.rb, app/models/manageiq/providers/openstack/cloud_manager/provision_workflow/dialog_field_validation.rb, content/miq_dialogs/miq_provision_openstack_dialogs_template.yaml, spec/models/manageiq/providers/openstack/cloud_manager/provision/configuration_spec.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1614567
Allow user to select Network Port or Cloud Network when provisioning an OpenStack cloud instance.
Related to 
https://github.com/ManageIQ/manageiq/pull/18303
https://github.com/ManageIQ/manageiq-ui-classic/pull/5103
=> bug 1614567: Allow user to select Network Port for provisioning

app/models/manageiq/providers/openstack/cloud_manager/cloud_volume.rb, app/models/manageiq/providers/openstack/storage_manager/cinder_manager.rb, spec/models/manageiq/providers/openstack/cloud_manager/cloud_volume_spec.rb
There's an RFE for supporting Cinder's volume extend action. I don't know if it'll be accepted, but I had time so why not be proactive about it. https://bugzilla.redhat.com/show_bug.cgi?id=1685063
Volume extension has to be done via a separate request from updating other fields. I've added it as part of `raw_update_volume` since the alternative would be having to add a new UI just for this purpose. The way this is set up, if updating the volume's attributes fail, the whole thing will fail. But if only extending fails, the rest of the update will succeed but you'll still get a message in the UI about the resize having failed. If that seems odd, we could probably set up unique notifications and exceptions for volume-extend so that you get a notification for the attribute update and a …
=> Support Cinder's volume-extend action

app/models/manageiq/providers/openstack/infra_manager/host/operations.rb
Host's unset_node_maintenance_queue method used user_id field on MiqTask which doesn't exist, changed to userid.
This should this failing CI.
=> Fix invalid field user_id on Miqtask

app/models/manageiq/providers/openstack/manager_mixin.rb
Fixes the ugly 404 error demonstrated in https://github.com/ManageIQ/manageiq-providers-openstack/issues/455
=> Add case for 404 error to ManagerMixin:translate_exception

spec/models/manageiq/providers/openstack/cloud_manager/provision_workflow_spec.rb, spec/models/manageiq/providers/openstack/cloud_manager/refresh_spec_common.rb, spec/models/manageiq/providers/openstack/cloud_manager/stubbed_refresher_spec.rb
Fixes broken tests caused by https://github.com/ManageIQ/manageiq/pull/18633 changing CloudManager::AuthKeyPair to inherit from Authentication instead of AuthPrivateKey.
=> Fix tests broken by #18633 changing the base class of AuthKeyPair

app/models/manageiq/providers/openstack/cloud_manager.rb
This PR causes `vm_create_snapshot` (used by the snapshot creation UI) to create snapshots in the instance's tenant's scope rather than the admin tenant's scope. It also stops `vm_create_snapshot` from creating a MIQ Snapshot which is not used in the Openstack CloudManager and which isn't cleaned up by the refresh process. 
https://bugzilla.redhat.com/show_bug.cgi?id=1685300
This PR does not change `vm_create_evm_snapshot` which appears only to be used by the SmartState vm scan.
=>  Create instance snapshots with the owner's project scope

lib/manageiq/providers/openstack/legacy/events/openstack_ceilometer_event_monitor.rb
@aufi I missed this while working on the previous PR, but it's part of the same fix.
=> Set panko flag when using settings.yml to define event service

app/models/manageiq/providers/openstack/cloud_manager.rb
This reverts commit 35cb19d5cb8c812ee67474fbcf45f15ca72276fe, which was mistakenly included in #462 and backported to gaprindashvili and hammer.
=> Revert "Don't create a MIQ Snapshot record when creating an OSP Snapshot"

app/models/manageiq/providers/openstack/cloud_manager.rb, app/models/manageiq/providers/openstack/inventory/parser/cloud_manager.rb, app/models/manageiq/providers/openstack/inventory/persister/definitions/cloud_collections.rb, spec/models/manageiq/providers/openstack/cloud_manager/refresh_spec_common.rb
Instance "snapshots" in Openstack are a collection of an image
and a set of volume snapshots. In Horizon these are managed
individually, but ManageIQ abstracts them into a "snapshot"
object with its own UI. These snapshots were not part of the
inventory refresh process and could get out of sync with
the Glance images they represented. This patch causes these
helper objects to be managed by the inventory refresh process.
=> Manage snapshots as part of the inventory refresh process

app/models/manageiq/providers/openstack/cloud_manager.rb, app/models/manageiq/providers/openstack/cloud_manager/provision_workflow.rb, app/models/manageiq/providers/openstack/cloud_manager/refresh_parser.rb, app/models/manageiq/providers/openstack/inventory/collector.rb, app/models/manageiq/providers/openstack/inventory/collector/cloud_manager.rb, app/models/manageiq/providers/openstack/inventory/collector/target_collection.rb, app/models/manageiq/providers/openstack/inventory/parser/cloud_manager.rb, app/models/manageiq/providers/openstack/inventory/parser/storage_manager/cinder_manager.rb, app/models/manageiq/providers/openstack/storage_manager/cinder_manager.rb, spec/models/manageiq/providers/openstack/cloud_manager/provision_workflow_spec.rb, spec/models/manageiq/providers/openstack/cloud_manager/stubbed_refresher_spec.rb
@Ladas @aufi Based on our previous conversation, this PR uses a `services` column to indicate which Openstack services know about an AZ with that name. This seems like a much simpler way to go, and if this looks good I'll put up the other PRs it depends on.
https://bugzilla.redhat.com/show_bug.cgi?id=1549128
=> Tag AvailabilityZones with the service(s) they belong to so that Cinder and Nova AZs can be identified

app/models/manageiq/providers/openstack/infra_manager/host.rb, spec/models/manageiq/providers/openstack/cloud_manager/vm_spec.rb, spec/models/manageiq/providers/openstack/identity_sync_mixin_spec.rb
The below changes are rails 5.0 and 5.1 compatible.
* Define through association before trying to use it 
* Pass id to AR::Base exists?/find, not AR::Base objs
=> Fix rails 5-1 errors

app/models/manageiq/providers/openstack/cloud_manager.rb
Fixes:
```
DEPRECATION WARNING: The behavior of `attribute_was` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `attribute_before_last_save` instead. (called from refresh_parent_infra_manager at /Users/joerafaniello/Code/manageiq-providers-openstack/app/models/manageiq/providers/openstack/cloud_manager.rb:66)
```
=> Fix 5.1 deprecation on attribute_was, not 5.0 compatible

spec/models/manageiq/providers/openstack/cloud_manager/refresh_worker_spec.rb
Found here: https://github.com/ManageIQ/manageiq-providers-amazon/pull/542
One of these specs is pointless now since the leaf will always create three. Unless Adam disagrees. I'm sure I'll hear about it if he does. 
Broken originally by https://github.com/ManageIQ/manageiq/pull/18842
=> The leaf class should be tested

app/models/manageiq/providers/openstack/inventory/parser/cloud_manager.rb
OpenStack can return an Array for block_device_mapping on a VM,
updating code to use first element if an Array is provided.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1727275
=> Fix block_device_mapping in Snapshots Refresh

lib/manageiq/providers/openstack/legacy/events/openstack_ceilometer_event_monitor.rb
OpenStack should expect timestamps in UTC. However some production environments
might work in different way. The safest way fix seems to be extend event_backread
feature with possibility to turn it off.
Event backread can be now turned off by setting :event_backread_seconds
settings option to number less than 1, e.g. 0.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1734338
=> Make events_backread switchable

lib/manageiq/providers/openstack/legacy/openstack_handle/handle.rb, spec/legacy/openstack_handle/handle_spec.rb
When OpenStack User's password was a Number, fog-core coerced it to Numeric type, which caused
HTTP 400 failure leading to print request malformed error message including the password.
This is a temporary solution before fog-side fix https://github.com/fog/fog-openstack/pull/493
gets released and properly tested.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1723180
=> Raise error for numeric-only passwords

config/settings.yml, lib/manageiq/providers/openstack/legacy/events/openstack_ceilometer_event_monitor.rb, spec/legacy/events/openstack_ceilometer_event_monitor_spec.rb
Multiple issues related to not processing new events appeared, partially
caused by slow processing of historical Events from OpenStack. Adding settings option
:event_skip_history to allow skip all events generated in OpenStack before OpenStack
was added as provider to ManageIQ.
Also, event backread was decreased from 15 to 5 seconds to speedup catchup with OpenStack Events.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1692892
=> Allow skip historical Events from OpenStack

app/models/manageiq/providers/openstack/inventory/persister/definitions/cloud_collections.rb
I noticed that targeted refresh of snapshots seems to wipe out all the snapshots except for the target, suggesting that the inventory system is treating this as a complete refresh. Manually setting the :complete flag in the collection definition solves the problem, but I'm puzzled why this is necessary here but not for other collections.
@agrare @Ladas any thoughts on why this would be needed for just this collection? I hunted around through the inventory_refresh repo but didn't discover any clues.
=> Set :complete=>false when doing targeted snapshot refresh

app/models/manageiq/providers/openstack/cloud_manager/vm/operations.rb, app/models/manageiq/providers/openstack/cloud_manager/vm/operations/guest.rb, app/models/manageiq/providers/openstack/cloud_manager/vm/operations/power.rb, app/models/manageiq/providers/openstack/cloud_manager/vm/operations/relocation.rb, app/models/manageiq/providers/openstack/infra_manager.rb, app/models/manageiq/providers/openstack/infra_manager/host.rb, spec/models/manageiq/providers/openstack/infra_manager/refresh_worker_spec.rb
update_attributes and update_attributes! are deprecated starting in Rails 6
See https://rubyinrails.com/2019/04/09/rails-6-1-activerecord-deprecates-update-attributes-methods/ for details and Rails PR links.
=> update_attributes deprecation

app/models/manageiq/providers/openstack/cloud_manager.rb
Error passed to UI by failed Snapshot create call was not displayed by UI correctly.
Updating error message with information parsed from original fog error.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1750558
=> Fix Snapshot create error message

app/models/manageiq/providers/openstack/cloud_manager/base_template.rb, app/models/manageiq/providers/openstack/cloud_manager/template.rb, app/models/manageiq/providers/openstack/cloud_manager/volume_snapshot_template.rb, app/models/manageiq/providers/openstack/cloud_manager/volume_template.rb, app/models/manageiq/providers/openstack/inventory/persister/definitions/cloud_collections.rb
Since the Cloud persister miq_template collection definition was using the 'MiqTemplate' model, all MiqTemplates were getting scooped up when attempting to reconnect archived templates. This PR specifies that only objects of the CloudManager's own Template type should be included.
=> Specify CloudManager::Template in Cloud persister definition

app/models/manageiq/providers/openstack/inventory/parser/cloud_manager.rb
If volume is mounted to a VM, but it doesn't have mountpoint to the VM, something
is wrong in OpenStack (e.g. failures with limits in migration), but our code should not fail
the refresh.
Adding skip volumes without mountpoint to VM parsing refresh code.
=> Skip Volumes without mountpoint in VM refresh

lib/manageiq/providers/openstack/legacy/events/openstack_ceilometer_event_monitor.rb, spec/legacy/events/openstack_ceilometer_event_monitor_spec.rb
OpenStack Eventing service Panko should accept flag all_tenants which provides
Events from all tenants. Unfortunately it doesn't work correctly with Keystone v2
auth (v3 is OK).
Skipping all_tenants flag in such case.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1740767
=> Don't send all_tenants flag for Panko with Keystone v2

app/models/manageiq/providers/openstack/inventory/parser/cloud_manager.rb
In Volume Template refresh, there is fallback for filling name attribute by ID
in case OpenStack name is nil. This was failing for undefined :id method.
Hash-like access was used in same way as primary identification of
Volume Template object few lines before.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1767423
=> Fix Volume Template nil name refresh

app/models/manageiq/providers/openstack/event_catcher_mixin.rb
This adds an exception handler to the `EventCatcherMixin#monitor_events` method. If it fails, it will properly log the issue instead of spewing a backtrace into the log. This occurred recently when connecting to an Openstack instance where Panko was missing.
Should it also call `stop_event_monitor` on an exception there? If you think so I can update the PR.
=> Add an exception handler to event monitoring

app/models/manageiq/providers/openstack/manager_mixin.rb
https://github.com/ManageIQ/manageiq/issues/18818
=> Add params_for_create and verify_credentials

app/models/manageiq/providers/openstack/network_manager/refresh_worker.rb, app/models/manageiq/providers/openstack/network_manager/refresh_worker/runner.rb
Refresh of the network manager is handled by the parent manager
refresh worker
see also: https://github.com/ManageIQ/manageiq/pull/19524
=> Remove unused sub-manager refresh worker

app/models/manageiq/providers/openstack/cloud_manager/event_target_parser.rb, app/models/manageiq/providers/openstack/inventory/collector.rb, app/models/manageiq/providers/openstack/inventory/collector/cloud_manager.rb, app/models/manageiq/providers/openstack/inventory/collector/target_collection.rb, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_fast_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_network_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_port_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_router_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_stack_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_tenant_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_vm_targeted_refresh.yml, spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_volume_targeted_refresh.yml
Authored by @Ladas from https://github.com/ManageIQ/manageiq-providers-openstack/pull/487
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1728624
=> Fix targeted refresh for nested stacks and their resource relations

app/models/manageiq/providers/openstack/cloud_manager/event_target_parser.rb, spec/models/manageiq/providers/openstack/cloud_manager/event_target_parser_spec.rb
Targeted refresh for Image is triggered but didn't update database with up-to-date Images status.
Updated Image ID parsing to use oslo.message as a fallback and added target association miq_templates which represents Images in MIQ.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1762866
=> Fix Image targeted refresh

app/models/manageiq/providers/openstack/infra_manager/event_parser.rb, app/models/manageiq/providers/openstack/infra_manager/host.rb, app/models/manageiq/providers/openstack/infra_manager/host/operations.rb, app/models/manageiq/providers/openstack/infra_manager/metrics_capture.rb, app/models/manageiq/providers/openstack/infra_manager/orchestration_stack.rb, app/models/manageiq/providers/openstack/infra_manager/refresh_parser.rb, app/models/manageiq/providers/openstack/inventory/parser/network_manager.rb, spec/models/manageiq/providers/openstack/cloud_manager/refresh_spec_common.rb, spec/models/manageiq/providers/openstack/infra_manager/refresher_rhos_juno_spec.rb
We are looking to remove ems_ref_obj since it was originally added to store the "full" VMware object reference
=> Remove ems_ref_obj

app/models/manageiq/providers/openstack/cloud_manager/cloud_volume.rb, app/models/manageiq/providers/openstack/cloud_manager/cloud_volume_backup.rb, spec/models/manageiq/providers/openstack/cloud_manager/cloud_volume_backup_spec.rb, spec/models/manageiq/providers/openstack/cloud_manager/cloud_volume_spec.rb
I expect this to be a partial fix (along with associated core PR) for https://bugzilla.redhat.com/show_bug.cgi?id=1748918, where a lack of notifications around Volume Backup actions is obscuring the reason for backup deletion failing.
Depends on https://github.com/ManageIQ/manageiq/pull/19357
=> Raise notifications when creating, restoring, and deleting backups

app/models/manageiq/providers/openstack/storage_manager/cinder_manager/event_target_parser.rb, spec/models/manageiq/providers/openstack/storage_manager/cinder_manager/event_target_parser_spec.rb
Bootable Volumes from OpenStack are modelled as CloudVolumes, but also as VolumeTemplates
what allows use it in new Instance provision. Targeted refresh refreshed only CloudVolumes.
Updating target collection to trigger refresh for VolumeTemplates too.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1770831
=> Update Targeted refresh for VolumeTemplate objects

manageiq-providers-openstack.gemspec
Update excon gem version to not older than v0.71 to avoid CVE-2019-16779.
=> Update excon gem dependency

app/models/manageiq/providers/openstack/base_metrics_capture.rb, app/models/manageiq/providers/openstack/cloud_manager/metrics_capture.rb, app/models/manageiq/providers/openstack/infra_manager/metrics_capture.rb, app/models/manageiq/providers/openstack/network_manager/metrics_capture.rb, spec/models/manageiq/providers/openstack/cloud_manager/metrics_capture_spec.rb
openstack is a cloud metrics capture class. subclassing the proper parent
part of ManageIQ/manageiq#19684
NOTE: this one is not open/shut like the others.
The hierarchy is a little odd. Especially since there is a `NetworkManager` with network capture
Wondering if this is good enough, or if we need to get into modules and the like
=> Subclass CloudManager metrics capture

app/models/manageiq/providers/openstack/manager_mixin.rb
Updating the initial DDF schema to look more similar to the current form's layout. Here are the catches:
* Keystone v2 as default API version - suggested by @aufi 
* Events type selection changed from `radio` to `select` because DDF doesn't do inline radios
* SSL enforcement dropdown doesn't allow to select an option - reported [here](https://github.com/ManageIQ/manageiq-ui-classic/issues/6656#issuecomment-584624556)
* No AMQP fallback hostnames - will be added after [this bug](https://bugzilla.redhat.com/show_bug.cgi?id=1801583) gets fixed
* Made API port for AMQP a required field
* RSA Private Key field is set to password as DDF doesn't do file uploads [yet](https://github.com/data-driven-forms/react-forms/issues/307)
**Old Default Endpoint:**
**Old AMQP Endpoint:**
**Old RSA …
=> Make the DDF fields more similar to the current form's layout + i18n

app/models/manageiq/providers/openstack/storage_manager/cinder_manager.rb
This is pluggable version of https://github.com/ManageIQ/manageiq/pull/19909
=> Add display name for cinder storage manager

spec/models/manageiq/providers/openstack/infra_manager/orchestration_stack_spec.rb, spec/models/manageiq/providers/openstack/openstack_stubs.rb
This removes a few invalid partials that aren't actually implemented, which will cause failures if strict partial validation is enabled.
Removing these had no effect.
=> Remove invalid partials from specs

lib/manageiq/providers/openstack/legacy/events/openstack_ceilometer_event_monitor.rb
Ceilometer/Panko Event monitor starts with the oldest events from OpenStack after each process
(re)start. Which leads to slow event catching up on larger deployments which can lead to temporarily
not working targeted refresh.
Fixing expression for ```@since``` timestamp initialization. To use last ems_event timestamp and if there is none, check skip_history? etc.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1812408
=> Fix not needed Events reloading after restart

app/models/manageiq/providers/openstack/infra_manager.rb, app/models/manageiq/providers/openstack/inventory/collector.rb, app/models/manageiq/providers/openstack/inventory/collector/cloud_manager.rb, app/models/manageiq/providers/openstack/inventory/collector/infra_manager.rb, app/models/manageiq/providers/openstack/inventory/collector/target_collection.rb, app/models/manageiq/providers/openstack/inventory/parser.rb, app/models/manageiq/providers/openstack/inventory/parser/cloud_manager.rb, app/models/manageiq/providers/openstack/inventory/parser/infra_manager.rb, app/models/manageiq/providers/openstack/inventory/persister.rb, app/models/manageiq/providers/openstack/inventory/persister/infra_manager.rb, config/settings.yml, spec/models/manageiq/providers/openstack/infra_manager/refresher_rhos_juno_spec.rb
This adds the option for graph refresh to the Openstack::InfraManager.
Depends:
Core issue: https://github.com/ManageIQ/manageiq/issues/19888
=> Add graph refresh to the OpenStack InfraManager

app/models/manageiq/providers/openstack/infra_manager/refresher.rb, app/models/manageiq/providers/openstack/storage_manager/cinder_manager/refresher.rb
The RefreshParser.ems_inv_to_hashes method was used by legacy refresh
and no longer needed
=> Remove unused ems_inv_to_hashes

lib/manageiq/providers/openstack/legacy/openstack_handle/handle.rb
If we fail to find a tenant that works the default_tenant_name method was return the list of tenant_names to the caller.
=> If we fail to find a tenant don't return an Array

app/models/manageiq/providers/openstack/refresh_parser_common/helper_methods.rb
A logic for catch/rescue errors for refresh uses @os_handle for warn logging.
RHV/ovirt provider uses OpenStack networking, but doesn't provide @os_handle.
Updating warn error output to ignore nil @os_handle to allow pass refresh
even with skipped records (as until how, just logging raised the error).
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1815479
=> Update Network Refresh error logging for not-OpenStack provider

lib/manageiq/providers/openstack/legacy/openstack_handle/handle.rb
If the keystone identity service is deployed without a region then passing `:openstack_region` will cause a missing endpoint failure.
=> Handle Keystone service without a region

app/models/manageiq/providers/openstack/cloud_manager/cloud_tenant.rb
Similar fixes to what was given in https://github.com/ManageIQ/manageiq/pull/20036 and https://github.com/ManageIQ/manageiq/pull/20045
```
DEPRECATION WARNING: Dangerous query method (method whose arguments are used as
raw SQL) called with non-attribute argument(s): "lower(description) ASC".
Non-attribute arguments will be disallowed in Rails 6.0. This method should not
be called with user-provided values, such as request parameters or model
attributes. Known-safe values can be passed by wrapping them in Arel.sql().
(called from default_security_group at app/models/manageiq/providers/openstack/cloud_manager/cloud_tenant.rb:62)
```
These deprecation warnings display in rails 5.2
These fixes work in 5.1
Links
-----
* Part of the Rails 5.2 effort: …
=> [CloudTenant] Fix "Dangerous query method"

app/models/manageiq/providers/openstack/inventory/collector/target_collection.rb
Fixes an error seen in rails 5.2 because it's more strict about validating
`includes` are associations:
```
ActiveRecord::AssociationNotFoundError:
Association named 'parent' was not found on ManageIQ::Providers::Openstack::CloudManager::Vm; perhaps you misspelled it?
```
Related to ManageIQ/manageiq#20032
Below, you can see all of the other "included" values is an association that can
be reflected on by the model, while :parent cannot.  Note, this was the case
with rails 5.1 and it must have silently discarded these bogus includes while
5.2 raises `ActiveRecord::AssociationNotFoundError`.
```
irb(main):001:0> vm_klass = ManageIQ::Providers::CloudManager::Vm
irb(main):002:0> vm_klass._reflect_on_association(:key_pairs)
irb(main):003:0> vm_klass._reflect_on_association(:network_ports) …
```
=> parent is a method, not an association, and cannot be included

app/models/manageiq/providers/openstack/infra_manager.rb
This is required for selecting the correct STI subclass in https://github.com/ManageIQ/manageiq/pull/20157
Related issue: https://github.com/ManageIQ/manageiq/issues/18818
=> Implemented authentication_class selection logic based on authtype

app/models/manageiq/providers/openstack/manager_mixin.rb
Parent issue: https://github.com/ManageIQ/manageiq/issues/18818
There's no file upload component yet in the current DDF version. After the v2 update, I can replace the secret text field with a file upload.
=> Adjusted DDF schema for create/edit and validation

app/models/manageiq/providers/openstack/infra_manager/host.rb
FIX: https://bugzilla.redhat.com/show_bug.cgi?id=1723864
Updated the bash condition which manageiq-ssh-util gem couldn't handle without errors.
=> Fix Openstack service status section for infra node

app/models/manageiq/providers/openstack/manager_mixin.rb
The `Endpoint` model has a `port` field, but in the AMQP vaidation it's referred as `api_port` which is not very consistent. The DDF schema should and uses the `port` version, as the data from the API arrives so. In order to make sure that the validation will get the port, I had to add a fallback.
I'm not sure if the string conversion is necessary, but the old forms were sending the value as a string, so I wanted to play it safe.
Parent issue: https://github.com/ManageIQ/manageiq/issues/18818
=> Ensure that the AMQP port gets properly to the validation in DDF

.travis.yml, manageiq-providers-openstack.gemspec
This gem requires the installation of a C library and shouldn't be required for other repos which don't use it
Follow-up to: https://github.com/ManageIQ/manageiq-providers-openstack/pull/556
=> Don't require qpid_proton in gemspec

app/models/manageiq/providers/openstack/manager_mixin.rb
Updating ManagerMixin raw_connect method to use more readable
switch statement instead of conditions.
Related to https://github.com/ManageIQ/manageiq-providers-openstack/pull/556
=> Refactor STF Event Monitor - service switch in manager mixin

app/models/manageiq/providers/openstack/infra_manager/host.rb
A small update that fixes bash `if` condition to use it with `sudo`.
In addition to https://github.com/ManageIQ/manageiq-providers-openstack/pull/585
Refers to https://github.com/ManageIQ/manageiq-providers-openstack/pull/586
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1723864
=> Fix bash condition for services list

app/models/manageiq/providers/openstack/manager_mixin.rb
Fixes the problem described here: https://github.com/ManageIQ/manageiq-ui-classic/pull/6698#issuecomment-634290544
Parent issue: https://github.com/ManageIQ/manageiq/issues/18818
=> Make the infra provider field in the DDF form clearable

manageiq-providers-openstack.gemspec
This updates the activesupport gem from 5.0.0 to 5.2.4. This addresses CVE-2020-8165, which apparently suffers from a potential issue with MemCacheStore and RedisCacheStore.
https://groups.google.com/forum/#!topic/rubyonrails-security/bv6fW4S0Y1c
=> Update activesupport requirement

app/models/manageiq/providers/openstack/manager_mixin.rb
This might cause issues when using MiQ with a language other than English.
Parent issue: https://github.com/ManageIQ/manageiq/issues/18818
=> Do not call gettext on DDF form select option values

app/models/manageiq/providers/openstack/cloud_manager/vm/operations.rb, spec/models/manageiq/providers/openstack/cloud_manager/vm_spec.rb
Needed for: https://github.com/ManageIQ/manageiq/pull/20222
=> Add supports terminate feature

app/models/manageiq/providers/openstack/storage_manager/cinder_manager.rb
When dealing with a CloudVolume that is owned by a storage manager we
should delegate collections owned by the CloudManager without having to
invoke the parent_manager directly.
Dependant: https://github.com/ManageIQ/manageiq-ui-classic/pull/7133
=> Delegate cloud_tenants to parent_manager from storage_manager

app/models/manageiq/providers/openstack/event_catcher_mixin.rb
Without setting the monitor_running concurrent event the main event_catcher worker thread doesn't ever leave the do_before_work_loop which means it can't be shutdown cleanly until the first event is raised.
Related to: https://github.com/ManageIQ/manageiq-providers-amazon/pull/633
=> Set the monitor_running event to unblock the main thread

tools/ci/before_install.sh
Follow-up for https://github.com/ManageIQ/manageiq-providers-openstack/pull/556 backport. Ivanchuk branch is using qpid_proton 0.26.0 in core repo
=> [IVANCHUK] Use qpid_proton 0.26.0 for Travis

app/models/manageiq/providers/openstack/cloud_manager/flavor.rb
Currently the supports :create/:delete features are enabled at the base Flavor model, however only Openstack implements these operations
Cross Repo Tests: https://github.com/ManageIQ/manageiq-cross_repo-tests/pull/149
Dependent PR: https://github.com/ManageIQ/manageiq/pull/20332
=> Move supports :create to Openstack provider repo

app/models/manageiq/providers/openstack/cloud_manager/event_parser.rb, app/models/manageiq/providers/openstack/cloud_manager/event_target_parser.rb, spec/models/manageiq/providers/openstack/cloud_manager/event_target_parser_spec.rb
@aufi @agrare Please review.
Some notes:
- This only handles the events in the CloudManager.  I was going to bump this higher as there's an EventTargetParser for the other managers as well, but I didn't know if that made sense.  If you think I should, I'll add to this PR.
- I didn't reuse the message_content method on purpose, because it does an EMS lookup.  Ultimately, I'd like to remove that lookup and just always process `oslo.message` if it's there, because a hash lookup is relatively cheap compared to an EMS lookup and if `oslo.message` is present it needs to be parsed anyway.  Since this would require a signature change, I opted for not doing that in this PR, and can do that in a follow up.  I did, however put the message_payload method next to the message_content method so that the …
=> Parse oslo.message in all events

app/models/manageiq/providers/openstack/cloud_manager/event_parser.rb, app/models/manageiq/providers/openstack/cloud_manager/event_target_parser.rb, app/models/manageiq/providers/openstack/event_parser_common.rb, app/models/manageiq/providers/openstack/infra_manager/event_parser.rb, app/models/manageiq/providers/openstack/network_manager/event_parser.rb, app/models/manageiq/providers/openstack/network_manager/event_target_parser.rb, app/models/manageiq/providers/openstack/storage_manager/cinder_manager/event_parser.rb, app/models/manageiq/providers/openstack/storage_manager/cinder_manager/event_target_parser.rb, spec/models/manageiq/providers/openstack/cloud_manager/event_target_parser_spec.rb, spec/models/manageiq/providers/openstack/network_manager/event_target_parser_spec.rb, spec/models/manageiq/providers/openstack/storage_manager/cinder_manager/event_target_parser_spec.rb, spec/support/ems_event_helper.rb
Consolidates the duplicated event parsing and oslo.message handling for all EventParsers and EventTargetParsers.
- Removes the unnecessary lookup and check of the ems and it's "amqp" role
- Handles oslo.message on events coming from anywhere, so tests were added for NetworkManager and CinderManager EventTargetParsers
- Makes it clearer that the NetworkManager and CinderManager event parser are exactly the same as the CloudManager
@agrare Please review.
=> Consolidate event parsing

app/models/manageiq/providers/openstack/infra_manager/event_parser.rb, spec/models/manageiq/providers/openstack/infra_manager/event_parser_spec.rb
Ideally the EventCatcher shouldn't hit the database to do queries, linking up events to inventory should be done by the event handler.
Depends on: https://github.com/ManageIQ/manageiq/pull/20348
=> Use event host_uid_ems instead of doing a db query

manageiq-providers-openstack.gemspec
more core ext's on 4.1.0
update for update sake
https://github.com/ManageIQ/more_core_extensions/compare/179bf40..e5b4501
- Added Ruby 2.7 support [[#79](https://github.com/ManageIQ/more_core_extensions/pull/79)]
- Added Process#pause, Process#resume, and Process#alive? [[#73](https://github.com/ManageIQ/more_core_extensions/pull/73)]
array added * `#compact_map` - Collect non-nil results from the block
array added `#tabular_sort` - Sorts an Array of Hashes by specific columns
hierarchy added `#descendant_get` - Returns the descendant with a given name
the two breaking changes:
- **BREAKING**: Moved Object#descendant_get to Class#descendant_get [[#75](https://github.com/ManageIQ/more_core_extensions/pull/75)]
- **BREAKING**: Removed deprecated Enumerable#stable_sort_by …
=> bump more core extensions

app/models/manageiq/providers/openstack/cloud_manager.rb
All snapshot methods except vm_remove_snapshot require the 'MiqOpenstackInstance' class, without this require the operation is faililng with an uninitialized constant error.
```
Failed to remove snapshot of test-snpsh-j8hs: uninitialized constant ManageIQ::Providers::Openstack::CloudManager::MiqOpenStackInstance
```
=> The vm_delete_snapshot method is missing a require

app/models/manageiq/providers/openstack/base_metrics_capture.rb
Metric resources for an Instance network interfaces are separated as "instance_network_resources" in
Gnocchi. ManageIQ searches for such resources across all resources and filters it later after the query.
Updating resources query to request only instance_network_resources (instead of default generic - https://github.com/fog/fog-openstack/blob/master/lib/fog/openstack/metric/requests/list_resources.rb) to reduce
amount of API response data and more efficient filtering which could fix network metrics loading on larger
OpenStack deployments.
Related to https://bugzilla.redhat.com/show_bug.cgi?id=1805020
=> Update metric network interface lookup

lib/manageiq/providers/openstack/legacy/openstack_handle/handle.rb
When determining the connection protocol for an Openstack connection, we now need to check explicitly for the string "ssl-no-validation", otherwise it will inadvertently set the protocol to "http" instead of "https".
This started happening as a result of the recent DDF form changes, because prior to that we used to just pass "ssl" as the string via the angular controller.
https://github.com/ManageIQ/manageiq-ui-classic/blob/ivanchuk/app/controllers/mixins/ems_common/angular.rb#L563-L569
To ensure backwards compatibility I've left the previous check for now.
Thanks go to Jay Carman for the spot and original patch via gitter.
=> Check for ssl-no-validation string

app/models/manageiq/providers/openstack/cloud_manager.rb, spec/models/manageiq/providers/openstack/cloud_manager_spec.rb
Since we were memoizing a dynamic value, subsequent changes were not reflected.
=> Fix bug where new providers are not reflected in the list

.yamllint
This was left over in the core repo's .yamllint file https://github.com/ManageIQ/manageiq/pull/20530/files#diff-b97c55dd898003930e2858fadd3b5c9cR5
=> Ignore the tools/openstack_data directory in yaml lint

spec/models/manageiq/providers/openstack/cloud_manager/cloud_volume_backup_spec.rb, spec/models/manageiq/providers/openstack/cloud_manager/cloud_volume_snapshot_spec.rb, spec/models/manageiq/providers/openstack/cloud_manager/cloud_volume_spec.rb, spec/models/manageiq/providers/openstack/cloud_manager/vm_spec.rb, spec/spec_helper.rb
Follow-up to https://github.com/ManageIQ/manageiq-providers-openstack/pull/636#discussion_r490535548
This was kind of a shortcut rather than seeding these only in tests which actually use NotificationTypes.  A number of tests do this already so I guess someone got fed-up with doing it one by one and just seeded them everytime?
=> Don't seed NotificationTypes in the main spec_helper

app/models/manageiq/providers/openstack/inventory/persister.rb
https://github.com/ManageIQ/manageiq/pull/20561 moved the tag mapper initialization to core so it doesn't have to be duplicated in every provider persister definition
=> Use the tag_mapper from the core Persister

app/models/manageiq/providers/openstack/cloud_manager.rb, app/models/manageiq/providers/openstack/infra_manager.rb
The default behavior for the `async-credentials` component is [changing to be optional](https://github.com/ManageIQ/manageiq-ui-classic/pull/7347), so it has to be explicitly marked as required here. This is a little different from any other provider, not just the default credentials are required as all the other components are only rendered when the user selects the right protocol from the dropdown.
=> Make the credentials required in the provider DDF

app/models/manageiq/providers/openstack/cloud_manager/cloud_volume.rb, app/models/manageiq/providers/openstack/helper_methods.rb, app/models/manageiq/providers/openstack/manager_mixin.rb, lib/manageiq/providers/openstack/legacy/openstack_handle/baremetal_delegate.rb, lib/manageiq/providers/openstack/legacy/openstack_handle/compute_delegate.rb, lib/manageiq/providers/openstack/legacy/openstack_handle/event_delegate.rb, lib/manageiq/providers/openstack/legacy/openstack_handle/handle.rb, lib/manageiq/providers/openstack/legacy/openstack_handle/handled_list.rb, lib/manageiq/providers/openstack/legacy/openstack_handle/identity_delegate.rb, lib/manageiq/providers/openstack/legacy/openstack_handle/image_delegate.rb, lib/manageiq/providers/openstack/legacy/openstack_handle/introspection_delegate.rb, lib/manageiq/providers/openstack/legacy/openstack_handle/metering_delegate.rb, lib/manageiq/providers/openstack/legacy/openstack_handle/metric_delegate.rb, lib/manageiq/providers/openstack/legacy/openstack_handle/multi_tenancy/base.rb, lib/manageiq/providers/openstack/legacy/openstack_handle/network_delegate.rb, lib/manageiq/providers/openstack/legacy/openstack_handle/nfv_delegate.rb, lib/manageiq/providers/openstack/legacy/openstack_handle/orchestration_delegate.rb, lib/manageiq/providers/openstack/legacy/openstack_handle/storage_delegate.rb, lib/manageiq/providers/openstack/legacy/openstack_handle/volume_delegate.rb, lib/manageiq/providers/openstack/legacy/openstack_handle/workflow_delegate.rb
At the moment it doesn't appear that the Openstack cloud provider is honoring default or openstack-specific proxy settings. As far as I can tell they're completely ignored.
~~WIP for now until I figure out why it's failing.~~
Steps to reproduce:
* Create a simple proxy server locally.
* Add openstack cloud provider.
* Update proxy settings in the advanced settings screen to use your local proxy settings.
* Refresh the provider and/or update authentication.
A basic proxy you can use to test:
```
#!/usr/bin/env ruby
require 'webrick'
require 'webrick/httpproxy'
proxy = WEBrick::HTTPProxyServer.new(Port: 8080) # Adjust port as desired.
trap 'INT'  do proxy.shutdown end
trap 'TERM' do proxy.shutdown end
proxy.start
```
Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1649903
Regarding …
=> Add proxy support to Openstack

spec/legacy/events/openstack_stf_event_monitor_spec.rb
Fixes #643
On CI, enforces the tests must run; on local dev will skip the tests unless qpid_proton is installed.  Either way, one can choose to skip the tests using rspec tags (i.e. `SPEC_OPTS="--tag ~qpid_proton"`)
=> Check qpid_proton installation on local machines before running tests

spec/legacy/events/openstack_stf_event_monitor_spec.rb, spec/spec_helper.rb
Followup to https://github.com/ManageIQ/manageiq-providers-openstack/pull/646, this uses an exclude filter in the `spec_helper.rb` to skip `qpid_proton` tags if the `qpid_proton` gem is not loaded.
This is a little cleaner, and will work for any other spec examples that might eventually get tagged.
If you're wondering why I have `require 'qpid_proton'` in a `before(:all)` block, it's because the filter works on examples. If you remove that then it will still try to load `qpid_proton` and again we're back to failure.
=> Update qpid_proton spec handling using exclude filter

app/models/manageiq/providers/openstack/cloud_manager.rb
Openstack was calling ensure_managers which builds the NetworkManager and calls ensure_managers_zone_and_provider_region which is overridden here to set the zone/region for all child managers but before the storage managers were being built.
Typically cloud_managers with child storage managers will override the `HasNetworkManagerMixin#ensure_managers` method to include initializing the child storage managers as well, see https://github.com/ManageIQ/manageiq-providers-amazon/blob/master/app/models/manageiq/providers/amazon/cloud_manager.rb#L77-L90
https://github.com/ManageIQ/manageiq/pull/20701 appears to have kept this "working" but very non-obviously
Fixes API spec failures: https://github.com/ManageIQ/manageiq-api/pull/940
=> Fix StorageManager initialization

app/models/manageiq/providers/openstack/cloud_manager.rb, app/models/manageiq/providers/openstack/cloud_manager/cloud_volume_type.rb, app/models/manageiq/providers/openstack/inventory/parser/storage_manager/cinder_manager.rb, app/models/manageiq/providers/openstack/storage_manager/cinder_manager.rb, app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume.rb, app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume/operations.rb, app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume_backup.rb, app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume_snapshot.rb, app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume_type.rb, spec/factories/ext_management_system.rb, spec/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume_backup_spec.rb, spec/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume_snapshot_spec.rb, spec/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume_spec.rb
These models belong to the Openstack::StorageManager::CinderManager but their class name indicates that they belong to the Openstack::CloudManager which is quite confusing.
Schema migration: https://github.com/ManageIQ/manageiq-schema/pull/532
Depends on: https://github.com/ManageIQ/manageiq/pull/20782
Ref: https://github.com/ManageIQ/manageiq-providers-openstack/pull/644#issuecomment-722281752
=> Move OpenStack CloudVolume* from CloudManager to CinderManager

app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume.rb
These were missed in https://github.com/ManageIQ/manageiq-providers-openstack/pull/664 causing CI issues in UI.
=> Remodulize missed references to CloudVolumeSnapshot

app/models/manageiq/providers/openstack/cloud_manager.rb
@Fryguy you're not gonna like this, but we need a way to query the API for this :disappointed: 
@miq-bot add_label enhancement, kasparov/no
=> Set the supports :auth_key_pair_create on the CloudManager

app/models/manageiq/providers/openstack/inventory/collector/target_collection.rb
If an Event like network.delete.end is received, targeted refresh tries find the network by a raw fog request method which doesn't handle Not Found error, that could break the refresh attempt.
<del>Updating to Fog's model method (network.get) which returns nil for Not Found error request - https://github.com/fog/fog-openstack/blob/master/lib/fog/openstack/network/models/networks.rb#L22-L28 - this requires bigger change also in full graph refresh - decided to keep current code</del>
Adding ```rescue``` block to handle Not Found Error from Fog and return nil (which is already expected that nil could be returned).
This could be related to https://bugzilla.redhat.com/show_bug.cgi?id=1896581, however we're not 100% sure whether this is the main problem on the BZ.
=> Update Network Targeted refresh to skip not found network

app/models/manageiq/providers/openstack/cloud_manager.rb, app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume.rb
This is an initial Cloud Volume form schema for the fields that are specific to the ibm-cloud-provided cloud volumes.
Parent issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/7334
=> Declared DDF schema for cloud volume creation and editing

app/models/manageiq/providers/openstack/inventory/parser/network_manager.rb
CF expected the wrong `device_owner` parameter from Neutron
Fix: https://bugzilla.redhat.com/show_bug.cgi?id=1896581
=> Change hardcoded router data to regex

app/models/manageiq/providers/openstack/cloud_manager/vm.rb
The snapshot form in ui-classic has too complex provider-specific logic to decide what fields to show, so I'm making this simpler by moving the ovirt-specific form into this repo. The API will be able to [expose](https://github.com/ManageIQ/manageiq-api/pull/943) this schema if asked.
=> Declared DDF schema for creating snapshots

app/models/manageiq/providers/openstack/cloud_manager/scanning/job.rb
Originally this started as a linter warning, but it appears to be a bug. The original warning was that the `user_event` variable wasn't being used. However, it also revealed that `start_user_event_message` doesn't actually do anything, it's just a string. Instead, I'm pretty sure we want `log_start_user_event_message`.
See https://github.com/ManageIQ/manageiq/blob/master/app/models/vm_scan.rb#L242-L256 for more info.
It's also up for debate as to whether or not we should also be calling a corresponding `log_end_user_event_message` which is only called in a different method.
=> Use log_start_user_event_message in Scanning::Job

app/models/manageiq/providers/openstack/cloud_manager.rb, app/models/manageiq/providers/openstack/inventory/collector/storage_manager.rb, app/models/manageiq/providers/openstack/inventory/collector/storage_manager/swift_manager.rb, app/models/manageiq/providers/openstack/inventory/parser/storage_manager.rb, app/models/manageiq/providers/openstack/inventory/parser/storage_manager/swift_manager.rb, app/models/manageiq/providers/openstack/inventory/persister/storage_manager.rb, app/models/manageiq/providers/openstack/inventory/persister/storage_manager/swift_manager.rb, app/models/manageiq/providers/openstack/storage_manager/swift_manager.rb, app/models/manageiq/providers/openstack/storage_manager/swift_manager/refresher.rb, app/models/manageiq/providers/openstack/swift_manager_mixin.rb
The SwiftManager refresh is unable to run without a parent_manager, refresh logic should be moved to openstack
Related:
Dependent:
=> Move SwiftManager to Openstack plugin

spec/models/manageiq/providers/openstack/cloud_manager/refresh_spec_common.rb
The environment_builders were moved into the openstack plugin and out of core, we need to update the require paths accordingly
The builders were moved as part of https://github.com/ManageIQ/manageiq-providers-openstack/pull/674
=> Fix the path to the environment_builders

app/models/manageiq/providers/openstack/network_manager.rb
There's also a method called [`create_network_router`](https://github.com/ManageIQ/manageiq-providers-openstack/blob/master/app/models/manageiq/providers/openstack/network_manager.rb#L135) so I really hope it doesn't cause any collision.
Depends on: https://github.com/ManageIQ/manageiq/pull/20958
Parent issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/6862
=> Add support for the create_network_router feature for network mgr

lib/manageiq/providers/openstack/engine.rb
The `$fog_log` has to respond to `#instrument`
```
13) ManageIQ::Providers::Openstack::InfraManager::Refresher will perform a full refresh
Failure/Error: Fog.const_get(service).new(opts)
Fog::Service::NotFound:
openstack has no compute service
--- Caused by: ---
NoMethodError:
undefined method `instrument' for #<VMDBLogger:0x00000000038f73e0>
./lib/manageiq/providers/openstack/legacy/openstack_handle/handle.rb:81:in `raw_connect'
```
Fixes: https://travis-ci.com/github/ManageIQ/manageiq-providers-openstack/jobs/472355101
=> Fix VMDBLogger NoMethodError "instrument"

app/models/manageiq/providers/openstack/cloud_manager.rb, app/models/manageiq/providers/openstack/storage_manager/cinder_manager.rb, app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume.rb
These were not adjusted since @agrare moved the `CloudVolume` under `CinderManager` which caused issues in the UI. @agrare I'm not entirely sure about the correctness of the `volume_availability_zones` but there was no other method delegated and I wasn't sure I have to delegate all of the AZs.
Parent issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/7334
@miq-bot add_label bug, kasparov/no
=> Adjust the support features and ddf schema after CloudVolume remodel

spec/models/manageiq/providers/openstack/cloud_manager/refresh_spec_common.rb
fix specs for the refactor of vms to use ancestry, not relationships
needs
https://github.com/ManageIQ/manageiq/pull/20788 
tested here: https://github.com/ManageIQ/manageiq-cross_repo-tests/pull/283
=> adjust relationship count in specs

app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume.rb
Fixes [this issue](https://github.com/ManageIQ/manageiq-ui-classic/pull/7399#issuecomment-773327230) in the new CloudVolume form.
=> Pass CloudVolumeType#name in the CloudVolume form instead of type

app/models/manageiq/providers/openstack/cloud_manager.rb, app/models/manageiq/providers/openstack/infra_manager.rb, app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume.rb
Because carbon has four different dropdowns, the DDF schemas need to have explicit `initialValue` or `includeEmpty` settings in order to make the form validation work.
=> Adjust empty/initial values for select fields in DDF schemas

app/models/manageiq/providers/openstack/manager_mixin.rb
The params passed in to `ems_connect?` sets `:default_port` but it then tries to use `:default_api_port` which is always `nil`.
This means that the `OpenstackHandle` will always default to 5000 for the port regardless of what is passed in to the UI.
=> Fix for the OpenStack port always being nil and defaulting to 5000

spec/models/manageiq/providers/openstack/cloud_manager_spec.rb
The correct parameter name is default_port not default_api_port, this spec was only checking the default port so it was passing.
Also add a spec that doesn't use the default port to confirm it is working
=> Fix default_api_port used in cloud_manager_spec

app/models/manageiq/providers/openstack/cloud_manager.rb, app/models/manageiq/providers/openstack/manager_mixin.rb
The domain_id is being passed in as uid_ems according to params_for_create but verify_credentials was looking for it in keystone_v3_domain_id
This was causing `.verify_credentials` to pass but later on `#verify_credentials` which was using the right domain_id would fail.
Similar issue as: https://github.com/ManageIQ/manageiq-providers-openstack/pull/698
=> Fix domain_id params / verify key mismatch

spec/models/manageiq/providers/openstack/cloud_manager/event_catcher_spec.rb, spec/models/manageiq/providers/openstack/infra_manager/event_catcher_spec.rb
Rather than stub ems.authentication_status_ok? and ems.supports?(:timeline) we can just create appropriate authentication records and set the capabilities
Required for: https://github.com/ManageIQ/manageiq/pull/21138
=> Don't stub authentication_status_ok? in event_catcher_spec

lib/manageiq/providers/openstack/legacy/openstack_handle/handle.rb
Detection of a service for given tenant could return multiple kind of errors potentially (like unauthorized, most likely only in cases when OpenStack policy files were customized), extending rescue to generic Error.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1935206
=> Extend error catching in detect_service for tenant

lib/manageiq/providers/openstack/legacy/openstack_handle/handle.rb
Detecting the default_tenant_name if that default isn't "admin" isn't being successfully returned as memoized successfully due the  the trailing `if`
Required for:
* https://github.com/iv1111/manageiq-providers-ibm_power_vc/pull/1
=> Fix service detection if there is no admin tenant

app/models/manageiq/providers/openstack/cloud_manager.rb, app/models/manageiq/providers/openstack/inventory/parser/cloud_manager.rb, app/models/manageiq/providers/openstack/inventory/persister/definitions/cloud_collections.rb
Replace hard-coded "openstack" vendor strings so that subclasses of the openstack refresh code can easily override them.
Required for:
* https://github.com/iv1111/manageiq-providers-ibm_power_vc/pull/2
=> Make it easier to subclass the Openstack refresh classes

app/models/manageiq/providers/openstack/inventory/parser/cloud_manager.rb, app/models/manageiq/providers/openstack/inventory/persister.rb, app/models/manageiq/providers/openstack/inventory/persister/definitions/cloud_collections.rb, app/models/manageiq/providers/openstack/inventory/persister/definitions/network_collections.rb, app/models/manageiq/providers/openstack/inventory/persister/definitions/storage_collections.rb, spec/models/manageiq/providers/openstack/cloud_manager/refresh_spec_common.rb
Rather than hard-code the various STI types we should be using the auto_model_class mechanism from the core persister
=> Don't hardcode STI class in refresh

app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume.rb, spec/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume_spec.rb
Follow-up to: https://github.com/ManageIQ/manageiq/pull/21181
This has been replaced with `supports :update`
=> Remove unused validate_update_volume

app/models/manageiq/providers/openstack/inventory/parser/network_manager.rb
Support Ovirt and PowerVS NetworkManager subclasses
Required for:
* https://github.com/ManageIQ/manageiq-providers-ovirt/pull/559
=> Don't hard-code network manager subclasses

app/models/manageiq/providers/openstack/network_manager/cloud_subnet.rb, spec/models/manageiq/providers/openstack/network_manager/cloud_subnet_spec.rb
Depends On: https://github.com/ManageIQ/manageiq-ui-classic/pull/7734
Changes `ems.networks` to `ems.cloud_networks`, similar to https://github.com/ManageIQ/manageiq-providers-nuage/pull/247
Also modifies the Allocation Pools and Host Routes fields to ensure the Cloud Subnet form is working correctly.
Before: 
After:
=> Modified Allocation Pools Field of Cloud Subnet Form

app/models/manageiq/providers/openstack/manager_mixin.rb
There are a number of issues that could cause login to return unauthorized including domain_id, username, password.
Just saying "username or password" is misleading as it could be something else wrong as well.
=> Fix the unauthorized login error message

app/models/manageiq/providers/openstack/network_manager/cloud_subnet.rb
- `delete_cloud_subnet_queue` was removed and added to core
Depends on:
=> Refactor delete subnet queue

app/models/manageiq/providers/openstack/network_manager.rb
- `create_cloud_subnet_queue` method lives in the provider code but it is unnecessary and can be moved to core
Depends on:
=> Refactor create cloud subnet queue

app/models/manageiq/providers/openstack/cloud_manager.rb
Fixed these console errors in the cloud provider form and changed implementation of hidden text-field.
=> Fixed react prop errors for cloud_manager

app/models/manageiq/providers/openstack/network_manager/cloud_network.rb
depends:
this is what it is called for other models
commentary:
It looks like we have one of each. And it looks like we are not consistent in our api between update and edit. So it could go either way but I just wanted to pick one and go from there.
@miq-bot cross-repo-tests ManageIQ/manageiq-api#1078
=> rename params_for_edit as params_for_update

app/models/manageiq/providers/openstack/storage_manager/swift_manager.rb, app/models/manageiq/providers/openstack/storage_manager/swift_manager/cloud_object_store_container.rb, app/models/manageiq/providers/openstack/storage_manager/swift_manager/cloud_object_store_object.rb
These models did not have Openstack SwiftManager subclasses.
NOTE this will require a schema migration to fixup existing records
Schema change:
=> Subclass CloudObjectStore(Container|Object) models under Openstack SwiftManager

app/models/manageiq/providers/openstack/cloud_manager.rb, app/models/manageiq/providers/openstack/manager_mixin.rb, spec/models/manageiq/providers/openstack/cloud_manager_spec.rb
We currently assume that if we can connect to OpenStack Compute then we will be able to connect to Ceilometer, however this isn't always the case
=> Validate ceilometer endpoint

app/models/manageiq/providers/openstack/cloud_manager.rb, app/models/manageiq/providers/openstack/cloud_manager/auth_key_pair.rb, app/models/manageiq/providers/openstack/cloud_manager/host_aggregate.rb, spec/models/manageiq/providers/openstack/cloud_manager/auth_key_pair_spec.rb
Required for:
* https://github.com/ManageIQ/manageiq-api/pull/1098
=> Use standard CRUD names for HostAggregate supports

app/models/manageiq/providers/openstack/inventory/persister/definitions/cloud_collections.rb
This causes any subclasses of openstack (e.g. powervc) to have the wrong type on their cloud_tenant records
We're already checking in specs that the cloud_tenant records have the appropriate class name for this repo
=> Don't hard code cloud_tenant STI type

app/models/manageiq/providers/openstack/inventory/parser/cloud_manager.rb, app/models/manageiq/providers/openstack/inventory/persister/definitions/cloud_collections.rb
Now that the core persister has a snapshots inventory collection we can use that rather than redefine it here
Follow-up to https://github.com/ManageIQ/manageiq/pull/21629
=> Use the snapshots collection from core

app/models/manageiq/providers/openstack/inventory/persister/target_collection.rb
The strategy is handled automatically for targeted persisters and with the add_network_collection changes we can drop the parent ivar weirdness around adding the network manager collections.
=> Cleanup the TargetCollection persister

app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume.rb
The options passed in to cloud_volume create/update have string keys when invoked from the API.
This was causing issues where the :display_name / :cloud_tenant weren't being picked up on because we were looking for symbol keys.
=> Symbolize key for cloud_volume CRUD options

app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume.rb
Due to API changes the Cloud volumes edit page was broken and would not load. This PR fixes this issue and allows the page to load correctly with all the fields that can't be edited set to disabled.
=> Fix storage manager edit

app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume.rb
When trying to create a cloud volume with size 0 it throws an error:
```
Expected([200, 202]) <=> Actual(400 Bad Request) excon.error.response
:body => "{\"badRequest\": {\"code\": 400, \"message\": \"Invalid input for field/attribute size. Value: 0. 0 is less than the minimum of 1\"}}" 
:cookies => [ ]
:headers => { "Connection" => "keep-alive" "Content-Length" => "125" "Content-Type" => "application/json" "Date" => "Fri, 04 Feb 2022 17:14:50 GMT" "Server" => "nginx/1.19.0" "x-compute-request-id" => "req-5e9566bc-6c44-43f3-80c0-a4a34171798f" "x-openstack-request-id" => "req-5e9566bc-6c44-43f3-80c0-a4a34171798f" }
:host => "192.168.0.23"
:local_address => "192.168.0.75"
:local_port => 61347
:path => "/v2/a72fca25a78d41e2ac1492e4f3a9bbb2/volumes"
:port => 8776
:reason_phrase => "Bad …
```
=> Fixed cloud volume minimum size

app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume.rb, spec/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume_spec.rb
Follow-up to https://github.com/ManageIQ/manageiq-providers-openstack/pull/768 now that I am able to test with the proper UI form after https://github.com/ManageIQ/manageiq-providers-openstack/pull/769
=> Fix CloudVolume Create - DDF sends cloud_tenant_id not cloud_tenant record

app/models/manageiq/providers/openstack/network_manager.rb
This is a child manager of a CloudManager and is not supported for create by itself.
This had `supports :create` incorrectly for a long time, but after https://github.com/ManageIQ/manageiq/pull/21573 started checking for it now it shows up as supported for creation.
=> The Openstack NetworkManager cannot be added standalone

app/models/manageiq/providers/openstack/cloud_manager.rb, app/models/manageiq/providers/openstack/swift_manager_mixin.rb
Similar in vein to #677
This was part of a very old more drastic PR that I wrote.
I noticed since cinder and swift already have this refactor here, implementing it for network manager makes sense
- Don't subclass from core NetworkManager. (mimics work already done for swift/cinder)
- Remove duplicate `ensure_swift_manager` (all of the ensures seem to be defined in the parent class right now
except for network manager
Keeping duplicate `ensure_network_manager`. It feels like it is best to define where it is actually used
=> Minor Cleanup child manager init/ensure_

app/models/manageiq/providers/openstack/manager_mixin.rb
Improve the error message returned in a number of cases when verifying credentials
Non-ssl to an SSL endpoint
Before:
After:
SSL Verify with self-signed cert:
Before:
After:
=> Improve error messages in verify_credentials

app/models/manageiq/providers/openstack/storage_manager/swift_manager/cloud_object_store_container.rb
part of: https://github.com/ManageIQ/manageiq-api/pull/1142
Moved fields to provider repo for the create cloud object store container form as well as add support for creating cloud object store container form.
Fields:
=> Added fields for cloud object store container form

app/models/manageiq/providers/openstack/storage_manager/swift_manager/cloud_object_store_container.rb
Fixed an issue in this form where the cloud tenant selection gets reset when the user changes the name value.
@miq-bot add_reviewer @agrare 
=> Fixed cloud tenant id for object store containers

app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume.rb
Fixed issues in the cloud volumes add/edit form where changing text fields results in the cloud tenant or cloud network selected options being reset.
@miq-bot add_reviewer @agrare 
=> Fixed cloud tenant ids for cloud volumes and cloud subnets

app/models/manageiq/providers/openstack/network_manager/cloud_subnet.rb
Added params for edit for the cloud subnet form. This change also fixes an issue in the ui where changing any of the text fields would reset the values of the select components.
@miq-bot add-label enhancement
=> Added params for edit for cloud subnets

.github/CODEOWNERS
Removing former team members from codeowners. We dont have write
permissions and want get rid of review requests github notification.
Sending greetings to the ManageIQ team!
=> Remove former team from CODEOWNERS

app/models/manageiq/providers/openstack/helper_methods.rb, app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume.rb, app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume/operations.rb, app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume_backup.rb, app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume_snapshot.rb
Cloud Volume Backup Create example:
Before:
After:
I need to go through the rest of the operations and make sure we are printing the "parsed" exception to the logs otherwise we end up with:
```
[----] E, [2022-04-06T14:52:40.085584 #38769:b4280] ERROR -- evm: MIQ(cloud_volume_controller-wait_for_task): Unable to create backup for Cloud Volume "test": Expected([200, 202]) <=> Actual(400 Bad Request)
excon.error.response
:body          => "{\"badRequest\": {\"code\": 400, \"message\": \"Invalid volume: Volume to be backed up must be available or in-use, but the current status is \\\"backing-up\\\".\"}}"
:cookies       => [
]
:headers       => {
"Connection"             => "keep-alive"
"Content-Length"         => "153"
"Content-Type"           => "application/json"
"Date" …
```
=> Improve OpenStack operations error parsing

app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume.rb
Companion PR to https://github.com/ManageIQ/manageiq-ui-classic/pull/8254
Part of the process for upgrading [_attach.html.haml](https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/views/vm_common/_attach.html.haml#L33) and [_detach.html.haml](https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/views/vm_common/_detach.html.haml#L25) to react as per https://github.com/ManageIQ/manageiq-ui-classic/issues/7603.
=> Add custom schema fields to Openstack attach cloud volume form

spec/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume_snapshot_spec.rb
we are not putting snapshot create requests directly onto the queue instead of going through cloud volume
Part of https://github.com/ManageIQ/manageiq-api/pull/1162
=> update cloud volume snapshot specs

app/models/manageiq/providers/openstack/inventory/persister/storage_manager/cinder_manager.rb
Set the parent manager properly by using add_cloud_collection for referencing vms, etc... from the cinder manager refresh
Required for:
* https://github.com/ManageIQ/manageiq/pull/21650
=> Use add_cloud_collection for cinder_manager

app/models/manageiq/providers/openstack/cloud_manager/event_catcher.rb, app/models/manageiq/providers/openstack/cloud_manager/event_catcher/runner.rb, app/models/manageiq/providers/openstack/event_catcher_mixin.rb, app/models/manageiq/providers/openstack/event_catcher_runner_mixin.rb, app/models/manageiq/providers/openstack/infra_manager/event_catcher.rb, app/models/manageiq/providers/openstack/infra_manager/event_catcher/runner.rb, app/models/manageiq/providers/openstack/network_manager/event_catcher.rb, app/models/manageiq/providers/openstack/network_manager/event_catcher/runner.rb, app/models/manageiq/providers/openstack/storage_manager/cinder_manager/event_catcher.rb, app/models/manageiq/providers/openstack/storage_manager/cinder_manager/event_catcher/runner.rb
Currently all Openstack EventCatchers copy&paste this `all_valid_ems_in_zone` override to check if the event service is available, move it to a mixin.
Steps:
1. Rename the current `EventCatcherMixin` -> `EventCatcherRunnerMixin` since it is included in the `EventCatcher::Runner` class
2. Move `all_valid_ems_in_zone` to a new `EventCatcherMixin`
Easier to review commit by commit
=> Move all valid ems in zone to mixin

app/models/manageiq/providers/openstack/cloud_manager.rb
The ceilometer service doesn't require a separate endpoint for connection information but we have to have some way of identifying that the event monitor type selected is ceilometer.  This has historically been done by creating a ceilometer endpoint but using the default authentication.
=> Fix ceilometer endpoint creation

app/models/manageiq/providers/openstack/cloud_manager.rb, app/models/manageiq/providers/openstack/event_catcher_mixin.rb, app/models/manageiq/providers/openstack/infra_manager.rb, app/models/manageiq/providers/openstack/manager_mixin.rb, app/models/manageiq/providers/openstack/network_manager.rb, app/models/manageiq/providers/openstack/storage_manager/cinder_manager.rb, spec/models/manageiq/providers/openstack/cloud_manager/event_catcher_spec.rb, spec/models/manageiq/providers/openstack/infra_manager/event_catcher_spec.rb
Currently sync_event_monitor_available runs in the `EventCatcher#all_valid_ems_in_zone` method which is run A. by MiqServer not in the worker zone and B. every sync_workers loop multiple times per minute.
It is more advantageous to run this in the verify_credentials method which is run on the ems_operations role in the right zone and also runs far less frequently.
We can still run `event_monitor_available` before starting the event_catcher in case something went wrong since the last verify_credentials run.
=> Improve event monitor available check

spec/models/manageiq/providers/openstack/cloud_manager/event_catcher_spec.rb, spec/models/manageiq/providers/openstack/cloud_manager/event_target_parser_spec.rb, spec/models/manageiq/providers/openstack/cloud_manager/metrics_capture_spec.rb, spec/models/manageiq/providers/openstack/cloud_manager/refresh_spec_helpers.rb, spec/models/manageiq/providers/openstack/cloud_manager/refresher_rhos_havana_errors_spec.rb, spec/models/manageiq/providers/openstack/infra_manager/event_catcher_spec.rb, spec/models/manageiq/providers/openstack/infra_manager/host_spec.rb, spec/models/manageiq/providers/openstack/infra_manager/metrics_capture_spec.rb, spec/models/manageiq/providers/openstack/infra_manager/refresher_rhos_juno_spec.rb, spec/models/manageiq/providers/openstack/network_manager/event_target_parser_spec.rb, spec/models/manageiq/providers/openstack/storage_manager/cinder_manager/event_target_parser_spec.rb, spec/models/metric/ci_mixin/capture_spec.rb
continuation of https://github.com/ManageIQ/manageiq/pull/21966
if we want the miq_server, no reason to extract guid/zone to then have to code around them.
=> Use EvmSpecHelper.local_server

lib/manageiq/providers/openstack/legacy/openstack_handle/handle.rb
The legacy code requires 'parallel'
But that is not always called in the tests. Or possibly production
This requires it to make sure it is present
```
NameError:
uninitialized constant Parallel
rspec ./spec/legacy/openstack_handle/handle_spec.rb:27 # OpenstackHandle::Handle errors from services ignores 404 errors from services
rspec ./spec/legacy/openstack_handle/handle_spec.rb:34 # OpenstackHandle::Handle errors from services ignores 404 errors from services returning arrays
```
---
Does seem like this should not be a problem as it is required by the parent file, but alas, I'm getting these errors locally.
I'm also getting a table not found error, so maybe my database is just not working correctly.
=> fix issue finding parallel

app/models/manageiq/providers/openstack/cloud_manager.rb
Fixed cloud provider form `isclearable` select field bug where the entire object is returned when an option is selected instead of just the selected value.
Before:
After:
@miq-bot add_reviewer @agrare 
@miq-bot add_reviewer @Fryguy
=> Fixed cloud provider form clearable select field

manageiq-providers-openstack.gemspec
Parallel v1.12.1 was released in 2017, we shouldn't require such an old dependency.
NOTE azure-armrest also has `~> 1.12.0` so we can't go straight to `~> 1.22`.  I opened https://github.com/ManageIQ/azure-armrest/pull/422 to bump that so that we can use 1.22.*  Once that is released we could go to `~> 1.22` here as well.  Up to @Fryguy on if he wants to just loosen this or wait for release of azure-armrest and go to 1.22 here
=> Loosen the version requirement for parallel

spec/legacy/openstack_handle/handle_spec.rb, spec/models/manageiq/providers/openstack/cloud_manager/auth_key_pair_spec.rb, spec/models/manageiq/providers/openstack/cloud_manager/flavor_spec.rb, spec/models/manageiq/providers/openstack/cloud_manager/provision/volume_attachment_spec.rb, spec/models/manageiq/providers/openstack/cloud_manager/vm_spec.rb
https://github.com/rspec/rspec-mocks/issues 1460
=> Ruby 3 support: rspec-mocks 3.10.3 requires "with" to be explicit with hashes vs. kwargs

app/models/manageiq/providers/openstack/network_manager/cloud_network.rb, spec/factories/cloud_network.rb
- part of the effort to move provider-specific code out of core repositories
@miq-bot add_labels refactoring, test
=> Refactor cloud network factories/methods from core

app/models/manageiq/providers/openstack/manager_mixin.rb
The class-level verify_credentials method takes DDF parameters with the port being an integer.  The ems_connect? method was assuming the port was a string so it was doing `params[:port].try(:strip)` which was returning `nil` for an integer.  This then used the default port `5000` since no port appeared to be passed.
The result is the class-level verify succeeds, then the instance-level fails.
=> Fix port for class-level verify_credentials

app/models/manageiq/providers/openstack/infra_manager/host.rb
depends upon:
`verify_credentials` is a copy paste of `::Host#verify_credentials`
(The only difference is it defaults to `ssh` instead of `ws`.
[22336] updates `Host` to set the default to `ssh`, so this code is no longer necessary.
Going to kick build after [22336] is merged
[22336]: https://github.com/ManageIQ/manageiq/pull/22336
=> use default verify_credentials implementation

app/models/manageiq/providers/openstack/cloud_manager/provision_workflow.rb
Allow child classes to override the `get_dialog_name_from_automate` method passing in the platform extra_attr
Required for:
* https://github.com/ManageIQ/manageiq-providers-ibm_cic/pull/31
=> Allow overrides of Openstack::ProvisionWorkflow class

app/models/manageiq/providers/openstack/inventory/persister/definitions/cloud_collections.rb
When a snapshot is taken of a VM an image is created on the OpenStack side.  We associate this as a snapshot record to the VM that created it.
If the VM is deleted then the lazy_find will return `nil` and a log or raise an exception depending on prod/dev.
We can mark vm_or_template as optional in the manager_ref since the snapshot uid is globally unique.
Fixes https://github.com/ManageIQ/manageiq-providers-openstack/issues/844
=> Allow a missing Snapshot#vm_or_template_id

app/models/manageiq/providers/openstack/cloud_manager.rb, app/models/manageiq/providers/openstack/infra_manager.rb, app/models/manageiq/providers/openstack/infra_manager/host/operations.rb, app/models/manageiq/providers/openstack/manager_mixin.rb
We hashed around some ideas for provider's validate_credentials
- Wanted to get Compute and Baremetal into there
- Wanted the logic for each of those to be specific
- I didn't touch the auth_type.nil? case - we can discuss.
- I didn't handle cinder or swift managers. Anything special there?
- I did not see an issue with `ActiveSupport::Concerns`, but it is wrong and was bugging me
=> Provider validate credentials

app/models/manageiq/providers/openstack/infra_manager.rb
The previous code determined if ironic was present.
If it was not, it succeeded, but provided a warning message.
#846 converted that to requiring both to work.
This deviates from the original course.
This PR goes back to the straight/default behavior of only verifying
credentials for the service requested and not adding additional verification
=> Use standard verify_credentials

app/models/manageiq/providers/openstack/infra_manager.rb
There is a typo for the baremetal service which is causing `verify_credentials` to fail, `BareMetal` should be `Baremetal` instead
```
[----] I, [2023-05-01T14:03:46.121823 #86507:9740]  INFO -- evm: MIQ(ManageIQ::Providers::Openstack::InfraManager#with_provider_connection) Connecting through ManageIQ::Providers::Openstack::InfraManager: [openstack-infra]
[----] E, [2023-05-01T14:08:53.566963 #86507:9740] ERROR -- evm: MIQ(ManageIQ::Providers::Openstack::InfraManager#verify_api_credentials) Error Class=NameError, Message=uninitialized constant Fog::BareMetal
Did you mean?  Fog::Baremetal
[----] W, [2023-05-01T14:08:57.902627 #86507:9740]  WARN -- evm: MIQ(ManageIQ::Providers::Openstack::InfraManager#authentication_check_no_validation) type: [:default] for [24] [openstack-infra] Validation …
```
=> Fix InfraManager authentication

spec/models/manageiq/providers/openstack/cloud_manager/host_aggregate_spec.rb
This was a bug.  `ManageIQ::Providers::Openstack::CloudManager::CloudVolume` resolved to `CloudVolume` in classic rails loader. With zeitwerk, this bug raises a NameError.
=> Fix incorrect constant name reference by referencing HostAggregate

lib/manageiq/providers/openstack/legacy/openstack_handle/handle.rb, manageiq-providers-openstack.gemspec, spec/legacy/openstack_handle/handle_spec.rb
The bug which this was added to workaround has been fixed in fog-openstack and we no longer need this.
Added by: https://github.com/ManageIQ/manageiq-providers-openstack/pull/504
Fog-openstack fixed by: https://github.com/fog/fog-openstack/pull/493 released in v1.0.9
Fixes https://github.com/ManageIQ/manageiq/issues/22683
=> Allow numberic-only passwords for keystone v3 again

spec/spec_helper.rb
`Gem.loaded_specs` has string keys which was causing this check to
always return false
```
(byebug) Gem.loaded_specs.key?(:qpid_proton)
false
(byebug) Gem.loaded_specs.key?("qpid_proton")
true
```
=> Fix Gem.loaded_specs looking for wrong key name

app/models/manageiq/providers/openstack/helper_methods.rb
The `:subject`, `:initiator`, and `:cause` attributes are all `belongs_to` associations on the `Notification` model and should not be stored in the `:options` yaml column.
This will need a data migration to clean up existing records
Ref: https://github.com/ManageIQ/manageiq-providers-openstack/pull/865#discussion_r1397169505
=> Don't store AR objects in Notification options

app/models/manageiq/providers/openstack/network_manager/metrics_collector_worker/runner.rb
The worker class for this runner was deleted long ago by https://github.com/ManageIQ/manageiq-providers-openstack/pull/548, remove the corresponding Runner class.
=> Delete an unused NetworkManager MetricsCollectorWorker Runner class

.rubocop_local.yml, app/models/manageiq/providers/openstack/cloud_manager.rb, spec/models/manageiq/providers/openstack/cloud_manager_spec.rb
Fix hostname_uniqueness_valid? failing if an `Openstack::InfraManager` has the same connection details as an `Openstack::CloudManager`
=> Only check for duplicate endpoints for CloudManagers

spec/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume_spec.rb
part of:
- https://github.com/ManageIQ/manageiq/pull/22898
Since we will be no longer storing the `unsupported_reason` in a temporary variable,
calling `supports?()` and `unsupported_reason()` each check the `supports :feature` code.
So in this test, it calls it 2 times.
I removed the stub to allow the ems to be called multiple times without freaking a stub out
Alternative would have been to add to the ems stub: `at_least(1).times`
=> fix spec for supports_feature change

spec/models/manageiq/providers/openstack/cloud_manager/provision/volume_attachment_spec.rb
Drops the rails 6.1 compatibility from:
https://github.com/ManageIQ/manageiq-providers-openstack/pull/885
=> Use Rails 7 way to set yaml permitted classes

.github/workflows/ci.yaml, bin/before_install
The lunar dist is no longer available, and installing from the noble dist instead (24.04) causes a conflict due to the version of libssl.
We can move the entire runner to ubuntu-24.04 to resolve the issue, this will be the default for ubuntu-latest "soon" :tm: https://github.com/actions/runner-images/issues/10636
> Rollout will begin on December 5th and will complete on January 17th, 2025.
Once that is complete we can revert back to using ubuntu-latest here.
Fixes https://github.com/ManageIQ/manageiq-providers-openstack/actions/runs/12258034148/job/34196883353
```
Ign:8 http://us.archive.ubuntu.com/ubuntu lunar InRelease
Err:9 http://us.archive.ubuntu.com/ubuntu lunar Release
404  Not Found [IP: 91.189.91.81 80]
Reading package lists...
E: The repository …
```
=> Use ubuntu-24.04 to fix libqpid-proton11

app/models/manageiq/providers/openstack/network_manager.rb, app/models/manageiq/providers/openstack/storage_manager/cinder_manager.rb, config/settings.yml
Reasoning here: https://github.com/ManageIQ/manageiq-providers-azure/pull/564#issuecomment-2445034651
@miq-bot add_label bug, radjabov/yes?
=> Delegate refresh_ems class method to parent cloud manager

.github/workflows/ci.yaml
This went back and forth a little bit but finally ubuntu-latest is ubuntu-24.04 so we don't need to use a specific version here.
Follow-up to https://github.com/ManageIQ/manageiq-providers-openstack/pull/897
=> Ubuntu-latest is 24.04 now
